-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonStats = ClassCodexArchonStats or {}
ClassCodexArchonStats["DEMONHUNTER"] = {
  ["devourer"] = {
    ["Mythic+"] = {
      targets = {
        crit = 561,
        haste = 918,
        mastery = 1031,
        versatility = 146,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 630,
        haste = 900,
        mastery = 997,
        versatility = 129,
      },
    },
  },
  ["havoc"] = {
    ["Mythic+"] = {
      targets = {
        crit = 1150,
        haste = 354,
        mastery = 981,
        versatility = 154,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 1146,
        haste = 379,
        mastery = 984,
        versatility = 142,
      },
    },
  },
  ["vengeance"] = {
    ["Mythic+"] = {
      targets = {
        crit = 728,
        haste = 995,
        mastery = 574,
        versatility = 248,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 722,
        haste = 1047,
        mastery = 619,
        versatility = 212,
      },
    },
  },
}
