-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexCraftingData = ClassCodexCraftingData or {}
ClassCodexCraftingData["DEMONHUNTER"] = {
  ["devourer"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          popular = true,
        },
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
          bis = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          popular = true,
        },
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
      },
    },
  },
  ["havoc"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244748,
          name = "Aetherlume Bands",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244593,
          name = "Smuggler's Reinforced Gloves",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
      },
    },
  },
  ["vengeance"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          bis = true,
          popular = true,
        },
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 237839,
          name = "Spellbreaker's Blade",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 237840,
          name = "Spellbreaker's Warglaive",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244586,
          name = "Smuggler's Leather Wristbands",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
      },
    },
  },
}
