-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["DEMONHUNTER"] = {
  ["devourer"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 237840,
              name = "Spellbreaker's Warglaive",
            },
          },
          {
            item = {
              itemId = 237840,
              name = "Spellbreaker's Warglaive",
            },
          },
          {
            item = {
              itemId = 271537,
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250031,
              name = "Devouring Reaver's Exhaustplates",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271538,
            },
          },
          {
            item = {
              itemId = 250030,
              name = "Devouring Reaver's Emblem",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 250035,
              name = "Devouring Reaver's Soul Flatteners",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 237840,
              name = "Spellbreaker's Warglaive",
            },
          },
          {
            item = {
              itemId = 237840,
              name = "Spellbreaker's Warglaive",
            },
          },
          {
            item = {
              itemId = 271537,
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250031,
              name = "Devouring Reaver's Exhaustplates",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271538,
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 250035,
              name = "Devouring Reaver's Soul Flatteners",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
  ["havoc"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 271537,
              name = "Abyssal Doomhound's Relentless Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250031,
              name = "Devouring Reaver's Exhaustplates",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271538,
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 250035,
              name = "Devouring Reaver's Soul Flatteners",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 240949,
              name = "Masterwork Sin'dorei Band",
            },
          },
          {
            item = {
              itemId = 193701,
              name = "Algeth'ar Puzzle Box",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 271537,
              name = "Abyssal Doomhound's Relentless Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250031,
              name = "Devouring Reaver's Exhaustplates",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271538,
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 250035,
              name = "Devouring Reaver's Soul Flatteners",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 249919,
              name = "Sin'dorei Band of Hope",
            },
          },
          {
            item = {
              itemId = 193701,
              name = "Algeth'ar Puzzle Box",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
        },
      },
    },
  },
  ["vengeance"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 271537,
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271535,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 250034,
              name = "Devouring Reaver's Essence Grips",
            },
          },
          {
            item = {
              itemId = 250030,
              name = "Devouring Reaver's Emblem",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 250035,
              name = "Devouring Reaver's Soul Flatteners",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 268292,
              name = "Sporelord's Mycelial Insignia",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 237840,
            },
          },
          {
            item = {
              itemId = 250033,
              name = "Devouring Reaver's Intake",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271535,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271540,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271538,
            },
          },
          {
            item = {
              itemId = 250030,
              name = "Devouring Reaver's Emblem",
            },
          },
          {
            item = {
              itemId = 271536,
            },
          },
          {
            item = {
              itemId = 249334,
              name = "Void-Claimed Shinkickers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249920,
              name = "Eye of Midnight",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 268292,
              name = "Sporelord's Mycelial Insignia",
            },
          },
        },
      },
    },
  },
}
