-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: murlok.io
ClassCodexMurlokPvp = ClassCodexMurlokPvp or {}
ClassCodexMurlokPvp["DEMONHUNTER"] = {
  ["devourer"] = {
    bracket = "solo",
    statPriority = {
      {
        key = "haste",
        rating = 1390,
      },
      {
        key = "versatility",
        rating = 903,
      },
      {
        key = "leech",
        rating = 249,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 239678,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 244559,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 240133,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 240952,
        },
      },
      ["Off Hand"] = {
        {
          itemId = 0,
        },
      },
      Prismatic = {
        {
          itemId = 240894,
        },
        {
          itemId = 241144,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270558,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 244557,
        },
      },
      Wrist = {
        {
          itemId = 244740,
        },
      },
    },
  },
  ["havoc"] = {
    bracket = "solo",
    statPriority = {
      {
        key = "mastery",
        rating = 1184,
      },
      {
        key = "versatility",
        rating = 909,
      },
      {
        key = "haste",
        rating = 171,
      },
      {
        key = "leech",
        rating = 122,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 239678,
        },
        {
          itemId = 270539,
        },
        {
          itemId = 270349,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 271538,
        },
        {
          itemId = 244559,
        },
        {
          itemId = 270511,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 240952,
        },
      },
      ["Off Hand"] = {
        {
          itemId = 0,
        },
      },
      Prismatic = {
        {
          itemId = 240902,
        },
        {
          itemId = 241144,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270558,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 244557,
        },
        {
          itemId = 270503,
        },
      },
      Wrist = {
        {
          itemId = 244740,
        },
        {
          itemId = 270500,
        },
      },
    },
  },
  ["vengeance"] = {
    bracket = "blitz",
    statPriority = {
      {
        key = "versatility",
        rating = 1136,
      },
      {
        key = "mastery",
        rating = 920,
      },
      {
        key = "leech",
        rating = 249,
      },
      {
        key = "haste",
        rating = 222,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 270538,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 270511,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 270532,
        },
      },
      ["Off Hand"] = {
        {
          itemId = 0,
        },
      },
      Prismatic = {
        {
          itemId = 240902,
        },
        {
          itemId = 241144,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270558,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 270503,
        },
      },
      Wrist = {
        {
          itemId = 244560,
        },
      },
    },
  },
}
