-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: Blizzard API, PvP season 42
ClassCodexBnetPvpTalents = ClassCodexBnetPvpTalents or {}
ClassCodexBnetPvpTalents["EVOKER"] = {
  ["augmentation"] = {
    brackets = {
      ["pvp-shuffle"] = {
        builds = {
          {
            exportString = "CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzgZYmZZGzMjZ2AAAAAAAAwMwMYM1YmZGAAAAYmZmxMzyYmBmhxwsMjllZZYmthZYmpRsgxMzMzMYwA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CEcBPJc41CfcseY0baneJ1IHrhZGbzMzMWmxMzsNMzMmZDAAAAADAAYGmZYMmaMzMDAAAAMjZYmZZMDwsYMYDWGDjtBwMRshxAzMwwA",
            heroTalent = "Scalecommander",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5560, 5563, 5561 },
          },
          {
            talents = { 5560, 5619, 5561 },
          },
          {
            talents = { 5561, 5563, 5560 },
          },
          {
            talents = { 5560, 5563, 5619 },
          },
          {
            talents = { 5560, 5561, 5454 },
          },
        },
      },
      ["pvp-blitz"] = {
        builds = {
          {
            exportString = "CEcBPJc41CfcseY0baneJ1IHrNMzMbzMzMWmxMzYYmZMAAAAAADAAMzwMDGDzYmZAAAAwMzYYmZZMzAzADz2M2WmlhZ2GmhZGDshxYmZmBDG",
            heroTalent = "Scalecommander",
          },
          {
            exportString = "CEcBPJc41CfcseY0baneJ1IHrhZGbzMzM2mxMzsMMzMmZDAAAAADAAMzMMzYMmaGzMDAAAAmZGYmZZMDwsghZbGbbzywMbDzwMTjYBjxMDAM",
            heroTalent = "Chronowarden",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5560, 5563, 5561 },
          },
          {
            talents = { 5561, 5612, 5560 },
          },
          {
            talents = { 5560, 5561, 5454 },
          },
        },
      },
    },
  },
  ["devastation"] = {
    brackets = {
      ["pvp-shuffle"] = {
        builds = {
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAgZMDMDzwMMzMGDTjZmpZmx2MMzMzMzMzAMzMDzMLjZgBGD2glxox2AyMBYDDMzAMA",
            heroTalent = "Scalecommander",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5462, 5464, 5469 },
          },
          {
            talents = { 5464, 5460, 5469 },
          },
          {
            talents = { 5469, 5460, 5462 },
          },
          {
            talents = { 5469, 5462, 5460 },
          },
          {
            talents = { 5460, 5462, 5464 },
          },
        },
      },
      ["pvp-blitz"] = {
        builds = {
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAgZMDMDzwMMzMGDTjZmpZmx2MMzMzMzMzAMzMDzMLjZgBmZmxGLWGzWjtZGmMT2AbDDMzAMA",
            heroTalent = "Scalecommander",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5469, 5460, 5462 },
          },
          {
            talents = { 5469, 5556, 5460 },
          },
          {
            talents = { 5469, 5462, 5460 },
          },
          {
            talents = { 5556, 5469, 5460 },
          },
          {
            talents = { 5460, 5469, 5456 },
          },
        },
      },
      ["pvp-2v2"] = {
        builds = {
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDmZwwMDMMzMTzYmJjxyMzMzwMzMzAmZGDzMLzMDmBMmBWALBzwEyGYZYAMzMMA",
            heroTalent = "Flameshaper",
          },
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDMDzwM8AzMYMTjZmpZMWmxMzMz8AzMzAmZmZYmZbMDMwYwGsMGN2GQmJAbYgZGgB",
            heroTalent = "Scalecommander",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5462, 5464, 5469 },
          },
          {
            talents = { 5469, 5460, 5464 },
          },
          {
            talents = { 5469, 5462, 5464 },
          },
          {
            talents = { 5469, 5460, 5462 },
          },
          {
            talents = { 5469, 5464, 5462 },
          },
        },
      },
      ["pvp-3v3"] = {
        builds = {
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAjZGzMzYGmhZmBjZaMzMNjxygZmZGzMzAMjZYmZZMDMwMzM2YzyY2asNzwkZyCYbYgZGYMA",
            heroTalent = "Scalecommander",
          },
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDmZwwMDMMzMTzYmJjxyMzMzwMzMzAmZGDzMLzMDmBMmBWALBzwEyGYZYAMzMMA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5462, 5469, 5464 },
          },
          {
            talents = { 5460, 5464, 5469 },
          },
          {
            talents = { 5469, 5460, 5464 },
          },
          {
            talents = { 5464, 5460, 5469 },
          },
          {
            talents = { 5460, 5469, 5464 },
          },
        },
      },
      ["pvp-rbg"] = {
        builds = {
          {
            exportString = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDmZwwMDMMzMTzYmJjxyMzMzwMzMzAmZGDzMLzMDmBMmBWALBzwEyGYZYAMzMMA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5462, 5460, 5469 },
          },
        },
      },
    },
  },
  ["preservation"] = {
    brackets = {
      ["pvp-shuffle"] = {
        builds = {
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYGGsNMAAYmhZmxYYmwMDAAAsNzMTzYMzMbjZAgxMjZW2YxCDzMz0QzmhFDjZGMzwA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYGmhlBAAYmZMzMYMzkZMAAAgtZmRzYmZmZZMDAMmZMz2GLWYYmZmGa2gNDjZGMzwA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5718, 5468, 5459 },
          },
          {
            talents = { 5468, 5718, 5461 },
          },
          {
            talents = { 5461, 5468, 5718 },
          },
          {
            talents = { 5468, 5461, 5718 },
          },
          {
            talents = { 5459, 5468, 5718 },
          },
        },
      },
      ["pvp-blitz"] = {
        builds = {
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAYmZWWGYGzMDzYGzsMGAAMzMjZmhZmZmgZAAAgtZmRYMzMLjZAAYMjNWgBmRDNgFYMzAwA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2WmZGDjxsZGw2wAAAzYGzYMMTMzMAAAgZmZyYmZmxYGAYMDsA2AzwEyGjNDzAMzwA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5718, 5468, 5459 },
          },
          {
            talents = { 5468, 5470, 5718 },
          },
          {
            talents = { 5470, 5718, 5468 },
          },
          {
            talents = { 5718, 5468, 5470 },
          },
          {
            talents = { 5459, 5470, 5718 },
          },
        },
      },
      ["pvp-2v2"] = {
        builds = {
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYmBsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmZsYYMzgZGGA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAegZmZ22GYYmZYmxgthBAAmhZmZGDzEmZAAAgtZmZaGjZmZZMDAMmZMzyGLWYYmZmGa2MsZYMzgZGGA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5459, 5468, 5718 },
          },
          {
            talents = { 5718, 5468, 5459 },
          },
          {
            talents = { 5718, 5459, 5468 },
          },
          {
            talents = { 5718, 5461, 5468 },
          },
          {
            talents = { 5459, 5718, 5468 },
          },
        },
      },
      ["pvp-3v3"] = {
        builds = {
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYmBsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmZsYYMzgZGGA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAegZmZ22GYYmZYmxgthBAAmhZmZGDzEmZAAAgtZmZaGjZmZZMDAMmZMzyGLWYYmZmGa2MsZYMzgZGGA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5718, 5468, 5459 },
          },
          {
            talents = { 5459, 5468, 5718 },
          },
          {
            talents = { 5468, 5718, 5459 },
          },
          {
            talents = { 5718, 5459, 5468 },
          },
          {
            talents = { 5468, 5461, 5718 },
          },
        },
      },
      ["pvp-rbg"] = {
        builds = {
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAegZmZ22GYYmZYGzYsNMAAwMjZmxMjZmwMAAAgtZmRzgZmZZMDAMmZMzyGL2YYmZmGa2gFDjZGMzwA",
            heroTalent = "Chronowarden",
          },
          {
            exportString = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYmxDgthBAAzMjZmxYYmYmZAAAgtZmRzgZmZZMDAMmZMzyGLWYYmZmGa2MsZYMzgZGGA",
            heroTalent = "Flameshaper",
          },
        },
        pvpTalentSets = {
          {
            talents = { 5468, 5718, 5470 },
          },
          {
            talents = { 5718, 5468, 5459 },
          },
          {
            talents = { 5470, 5718, 5459 },
          },
          {
            talents = { 5470, 5468, 5718 },
          },
          {
            talents = { 5468, 5718, 5711 },
          },
        },
      },
    },
  },
}
