-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexCraftingData = ClassCodexCraftingData or {}
ClassCodexCraftingData["EVOKER"] = {
  ["augmentation"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251488,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244580,
          name = "Farstrider's Brilliant Plumes",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251488,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
      },
    },
  },
  ["devastation"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 244589,
          name = "Scout's Scaled Bracers",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 251488,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244608,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
      },
    },
  },
  ["preservation"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244582,
          name = "Farstrider's Reinforced Faulds",
        },
      },
      embellishments = {
        {
          itemId = 0,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 237849,
          name = "Magister's Valediction",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244578,
          name = "Farstrider's Scouting Vest",
        },
        {
          itemId = 244580,
          name = "Farstrider's Brilliant Plumes",
        },
        {
          itemId = 244582,
          name = "Farstrider's Reinforced Faulds",
        },
        {
          itemId = 244597,
          name = "Scout's Polished Spaulders",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 241140,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
      },
    },
  },
}
