-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["EVOKER"] = {
  ["augmentation"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251178,
              name = "Ceremonial Hexblade",
            },
          },
          {
            item = {
              itemId = 249276,
              name = "Grimoire of the Eternal Light",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 249995,
              name = "Beacons of the Black Talon",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271504,
              name = "Searing Caldera of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
            bis = true,
          },
          {
            item = {
              itemId = 49810,
              name = "Scabrous Zombie Belt",
            },
          },
          {
            item = {
              itemId = 271500,
              name = "Earthen Pillars of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 249999,
              name = "Spelltreads of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 49812,
              name = "Purloined Wedding Ring",
            },
          },
          {
            item = {
              itemId = 249810,
              name = "Shadow of the Empyrean Requiem",
            },
          },
          {
            item = {
              itemId = 250223,
              name = "Soulcatcher's Charm",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 251178,
              name = "Ceremonial Hexblade",
            },
          },
          {
            item = {
              itemId = 249276,
              name = "Grimoire of the Eternal Light",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271499,
              name = "Calamitous Echo's Sundered Peaks",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 250000,
              name = "Frenzyward of the Black Talon",
            },
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
            bis = true,
          },
          {
            item = {
              itemId = 49810,
              name = "Scabrous Zombie Belt",
            },
          },
          {
            item = {
              itemId = 271500,
              name = "Earthen Pillars of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 249999,
              name = "Spelltreads of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 49812,
              name = "Purloined Wedding Ring",
            },
          },
          {
            item = {
              itemId = 249810,
              name = "Shadow of the Empyrean Requiem",
            },
          },
          {
            item = {
              itemId = 250223,
              name = "Soulcatcher's Charm",
            },
          },
        },
      },
    },
  },
  ["devastation"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251178,
              name = "Ceremonial Hexblade",
            },
          },
          {
            item = {
              itemId = 249276,
              name = "Grimoire of the Eternal Light",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271499,
              name = "Calamitous Echo's Sundered Peaks",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271504,
              name = "Searing Caldera of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
            bis = true,
          },
          {
            item = {
              itemId = 49810,
              name = "Scabrous Zombie Belt",
            },
          },
          {
            item = {
              itemId = 249996,
              name = "Greaves of the Black Talon",
            },
          },
          {
            item = {
              itemId = 249999,
              name = "Spelltreads of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 49812,
              name = "Purloined Wedding Ring",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 251178,
              name = "Ceremonial Hexblade",
            },
          },
          {
            item = {
              itemId = 249276,
              name = "Grimoire of the Eternal Light",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 249995,
              name = "Beacons of the Black Talon",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271504,
              name = "Searing Caldera of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
            bis = true,
          },
          {
            item = {
              itemId = 49810,
              name = "Scabrous Zombie Belt",
            },
          },
          {
            item = {
              itemId = 271500,
              name = "Earthen Pillars of Calamity",
            },
            bis = true,
          },
          {
            item = {
              itemId = 249999,
              name = "Spelltreads of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 49812,
              name = "Purloined Wedding Ring",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
  ["preservation"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 273778,
              name = "Polished Lightwood Channeler",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271499,
              name = "Calamitous Echo's Sundered Peaks",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271504,
              name = "Searing Caldera of Calamity",
            },
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
          },
          {
            item = {
              itemId = 249994,
              name = "Girdle of the Black Talon",
            },
          },
          {
            item = {
              itemId = 249996,
              name = "Greaves of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268287,
              name = "Grudgefiend Stompers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251136,
              name = "Signet of Snarling Servitude",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249809,
              name = "Locus-Walker's Ribbon",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 273780,
              name = "Venom-Etched Crescent",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 271501,
              name = "Calamitous Echo's Magmashapers",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271499,
              name = "Calamitous Echo's Sundered Peaks",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 244609,
              name = "World Tender's Trunkplate",
            },
          },
          {
            item = {
              itemId = 244584,
              name = "Farstrider's Plated Bracers",
            },
          },
          {
            item = {
              itemId = 271502,
              name = "Calamitous Echo's Ebon Greathorns",
            },
          },
          {
            item = {
              itemId = 244611,
              name = "World Tender's Barkclasp",
            },
          },
          {
            item = {
              itemId = 249996,
              name = "Greaves of the Black Talon",
            },
          },
          {
            item = {
              itemId = 268287,
              name = "Grudgefiend Stompers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251136,
              name = "Signet of Snarling Servitude",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249809,
              name = "Locus-Walker's Ribbon",
            },
          },
        },
      },
    },
  },
}
