-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: wowhead.com
ClassCodexGearData = ClassCodexGearData or {}
ClassCodexGearData["DEATHKNIGHT"] = {
  ["blood"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268213,
              name = "Maze-roa, Warlord's Fury",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Head",
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            source = "Nek'zali the Soulcoiler",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            source = "Temple of Sethraliss",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            source = "Crafting",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            source = "King's Rest",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271878,
              name = "Chausses of Unbound Rancor",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 273777,
              name = "Poison-Proof Stompers",
            },
            source = "Altar of Fangs",
          },
          {
            slot = "Ring ({251487})",
            item = {
              itemId = 240949,
              name = "Masterwork Sin'dorei Band",
            },
            source = "Crafting",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 251194,
              name = "Lightwarden's Bind",
            },
            source = "Blinding Vale",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Ring",
            item = {
              itemId = 159459,
              name = "Ritual Binder's Ring",
            },
            source = "King's Rest",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
            },
            source = "Voidscar Arena",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "A",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 250238,
        tier = "A",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "A",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 273797,
        tier = "A",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 270164,
        tier = "A",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 274493,
        tier = "A",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 158367,
        tier = "A",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 250245,
        tier = "B",
        name = "Tumor of the Swarm",
        contexts = { "dungeon" },
      },
      {
        itemId = 270168,
        tier = "B",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 270163,
        tier = "B",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
      {
        itemId = 251783,
        tier = "B",
        name = "Lost Idol of the Hash'ey",
        contexts = { "delves" },
      },
      {
        itemId = 250228,
        tier = "B",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "C",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "C",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 250244,
        tier = "D",
        name = "Permafrost Essence",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      food = {
        itemId = 242273,
        name = "Blooming Feast",
      },
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
      combatPotion = {
        itemId = 241288,
        name = "Potion of Recklessness",
      },
    },
    enchants = {
      {
        slot = "Helm",
        best = {
          itemId = 243981,
          name = "Enchant Helm - Empowered Blessing of Speed",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 243963,
          name = "Enchant Shoulders - Akil'zon's Swiftness",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Feet",
        best = {
          itemId = 244009,
          name = "Enchant Boots - Farstrider's Hunt",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243987,
          name = "Enchant Ring - Nature's Fury",
        },
      },
      {
        slot = "Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240890,
          name = "Flawless Deadly Peridot",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 242273,
          name = "Blooming Feast",
        },
      },
    },
  },
  ["frost"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268202,
              name = "Jaw of the Shackled Goddess",
            },
            source = "Ula'tek",
          },
          {
            slot = "Offhand",
            item = {
              itemId = 268209,
              name = "Aman'muso, Warlord's Vengeance",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Head",
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
              bonusIDs = { 8793, 8960, 12214, 13454, 13750, 13751, 13836, 12497 },
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271878,
              name = "Chausses of Unbound Rancor",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268260,
              name = "Scaled Fiend's Warboots",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 251513,
              name = "Loa Worshiper's Band",
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 273797,
        tier = "A",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250238,
        tier = "A",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 270165,
        tier = "B",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "B",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 270168,
        tier = "C",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 250228,
        tier = "C",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "C",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "D",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "D",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 158367,
        tier = "D",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "D",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "D",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
    },
    consumables = {
      flask = {
        itemId = 241326,
        name = "Flask of the Shattered Sun",
      },
      combatPotion = {
        itemId = 271884,
        name = "Concentrated Silvermoon Health Potion",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
      augmentRune = {
        itemId = 259085,
        name = "Void-Touched Augment Rune",
      },
    },
    enchants = {
      {
        slot = "Shoulders",
        best = {
          itemId = 243963,
          name = "Enchant Shoulders - Akil'zon's Swiftness",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 243981,
          name = "Enchant Helm - Empowered Blessing of Speed",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 244009,
          name = "Enchant Boots - Farstrider's Hunt",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240908,
          name = "Flawless Masterful Garnet",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241326,
          name = "Flask of the Shattered Sun",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241308,
          name = "Light's Potential",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 241304,
          name = "Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 242275,
          name = "Royal Roast",
        },
      },
    },
  },
  ["unholy"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268213,
              name = "Maze-roa, Warlord's Fury",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Head",
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            source = "Crafting",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271878,
              name = "Chausses of Unbound Rancor",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 237828,
              name = "Spellbreaker's March",
            },
            source = "Crafting",
          },
          {
            slot = "Ring",
            item = {
              itemId = 273792,
              name = "Band of the Amani Warlord",
            },
            source = "Altar of Fangs",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
            },
            source = "Voidscar Arena",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270164,
        tier = "A",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 250228,
        tier = "A",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 273797,
        tier = "A",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 245829,
        tier = "A",
        name = "Darkmoon Deck: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 251783,
        tier = "B",
        name = "Lost Idol of the Hash'ey",
        contexts = { "delves" },
      },
      {
        itemId = 245855,
        tier = "B",
        name = "Darkmoon Deck: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 193757,
        tier = "B",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "B",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 251792,
        tier = "B",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 274497,
        tier = "B",
        name = "Spirit-Rending Poison",
        contexts = { "delves" },
      },
      {
        itemId = 245750,
        tier = "C",
        name = "Darkmoon Deck: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 251782,
        tier = "C",
        name = "Withered Saptor's Paw",
        contexts = { "delves" },
      },
      {
        itemId = 250238,
        tier = "C",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "C",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
      {
        itemId = 250462,
        tier = "C",
        name = "Forgotten Farstrider's Insignia",
        contexts = { "raid" },
      },
      {
        itemId = 274493,
        tier = "C",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 270168,
        tier = "C",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 274496,
        tier = "C",
        name = "Ophidian Bone Whistle",
        contexts = { "delves" },
      },
      {
        itemId = 273796,
        tier = "C",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "C",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "C",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250245,
        tier = "C",
        name = "Tumor of the Swarm",
        contexts = { "dungeon" },
      },
      {
        itemId = 158367,
        tier = "C",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 280123,
        tier = "C",
        name = "Sharp Axe Holster",
        contexts = { "delves" },
      },
      {
        itemId = 251791,
        tier = "D",
        name = "Holy Retributor's Order",
        contexts = { "delves" },
      },
      {
        itemId = 251787,
        tier = "D",
        name = "Sealed Chaos Urn",
        contexts = { "delves" },
      },
      {
        itemId = 241340,
        tier = "D",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 245846,
        tier = "D",
        name = "Darkmoon Deck: Rot",
        contexts = { "crafting" },
      },
    },
    consumables = {
      combatPotion = {
        itemId = 241289,
        name = "Potion of Recklessness",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
      flask = {
        itemId = 241326,
        name = "Flask of the Shattered Sun",
      },
    },
    enchants = {
      {
        slot = "Helmet",
        best = {
          itemId = 243981,
          name = "Enchant Helm - Empowered Blessing of Speed",
        },
      },
      {
        slot = "Shoulder",
        best = {
          itemId = 243963,
          name = "Enchant Shoulders - Akil'zon's Swiftness",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 244009,
          name = "Enchant Boots - Farstrider's Hunt",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241322,
          name = "Flask of the Magisters",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 241304,
          name = "Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255845,
          name = "Silvermoon Parade",
        },
      },
      {
        slot = "Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240908,
          name = "Flawless Masterful Garnet",
        },
      },
    },
  },
}
