-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["DEATHKNIGHT"] = {
  ["blood"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 237846,
              name = "Blood Knight's Warblade",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            bis = true,
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268289,
              name = "Girdle of Devouring Rot",
            },
          },
          {
            item = {
              itemId = 249969,
              name = "Relentless Rider's Legguards",
            },
          },
          {
            item = {
              itemId = 193728,
              name = "Scaleguard's Stalwart Greatboots",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 237846,
              name = "Blood Knight's Warblade",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            bis = true,
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268289,
              name = "Girdle of Devouring Rot",
            },
          },
          {
            item = {
              itemId = 249969,
              name = "Relentless Rider's Legguards",
            },
          },
          {
            item = {
              itemId = 249381,
              name = "Greaves of the Unformed",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
    },
  },
  ["frost"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 237839,
              name = "Spellbreaker's Blade",
            },
          },
          {
            item = {
              itemId = 237839,
              name = "Spellbreaker's Blade",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 249971,
              name = "Relentless Rider's Bonegrasps",
            },
          },
          {
            item = {
              itemId = 249967,
              name = "Relentless Rider's Chain",
            },
          },
          {
            item = {
              itemId = 271473,
              name = "Baleful Grave-Knight's Greaves",
            },
          },
          {
            item = {
              itemId = 249381,
              name = "Greaves of the Unformed",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 237839,
              name = "Spellbreaker's Blade",
            },
          },
          {
            item = {
              itemId = 237839,
              name = "Spellbreaker's Blade",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268289,
              name = "Girdle of Devouring Rot",
            },
          },
          {
            item = {
              itemId = 249969,
              name = "Relentless Rider's Legguards",
            },
          },
          {
            item = {
              itemId = 249381,
              name = "Greaves of the Unformed",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
    },
  },
  ["unholy"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251168,
              name = "Liferipper's Cutlass",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            bis = true,
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268289,
              name = "Girdle of Devouring Rot",
            },
          },
          {
            item = {
              itemId = 249969,
              name = "Relentless Rider's Legguards",
            },
          },
          {
            item = {
              itemId = 249381,
              name = "Greaves of the Unformed",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 240949,
              name = "Masterwork Sin'dorei Band",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 249277,
              name = "Bellamy's Final Judgement",
            },
          },
          {
            item = {
              itemId = 271474,
              name = "Baleful Grave-Knight's Casque",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271472,
              name = "Baleful Grave-Knight's Gibbets",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271477,
              name = "Baleful Grave-Knight's Breastplate",
            },
            bis = true,
          },
          {
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271475,
              name = "Baleful Grave-Knight's Deathgrips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268289,
              name = "Girdle of Devouring Rot",
            },
          },
          {
            item = {
              itemId = 249969,
              name = "Relentless Rider's Legguards",
            },
          },
          {
            item = {
              itemId = 249381,
              name = "Greaves of the Unformed",
            },
          },
          {
            item = {
              itemId = 193708,
              name = "Platinum Star Band",
            },
          },
          {
            item = {
              itemId = 249919,
              name = "Sin'dorei Band of Hope",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249344,
              name = "Light Company Guidon",
            },
          },
        },
      },
    },
  },
}
