-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonStats = ClassCodexArchonStats or {}
ClassCodexArchonStats["PALADIN"] = {
  ["holy"] = {
    ["Mythic+"] = {
      targets = {
        crit = 573,
        haste = 832,
        mastery = 869,
        versatility = 248,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 474,
        haste = 857,
        mastery = 1191,
        versatility = 181,
      },
    },
  },
  ["protection"] = {
    ["Mythic+"] = {
      targets = {
        crit = 729,
        haste = 927,
        mastery = 563,
        versatility = 256,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 706,
        haste = 1042,
        mastery = 578,
        versatility = 243,
      },
    },
  },
  ["retribution"] = {
    ["Mythic+"] = {
      targets = {
        crit = 816,
        haste = 707,
        mastery = 976,
        versatility = 154,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 853,
        haste = 715,
        mastery = 1006,
        versatility = 130,
      },
    },
  },
}
