-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: wowhead.com
ClassCodexGearData = ClassCodexGearData or {}
ClassCodexGearData["PALADIN"] = {
  ["holy"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268211,
              name = "Baleful Hexblade",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Shield",
            item = {
              itemId = 268262,
              name = "Bubblefin Splash Guard",
            },
            source = "Nymrissa Wavecaller",
          },
          {
            slot = "Head",
            item = {
              itemId = 271465,
              name = "Warhelm of the Consecrated Flame",
            },
            source = "Murder Row",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271463,
              name = "Pauldrons of the Consecrated Flame",
            },
            source = "Murder Row",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271468,
              name = "Bulwark of the Consecrated Flame",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 268239,
              name = "Shellbound Bracers",
            },
            source = "The Lost Explorers",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271466,
              name = "Gauntlets of the Consecrated Flame",
            },
            source = "Entombed Sentinels",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271464,
              name = "Greaves of the Consecrated Flame",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268260,
              name = "Scaled Fiend's Warboots",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
            },
            source = "Voidscar Arena",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270162,
              name = "Soulcoiler Ritual Vessel",
            },
            source = "Nek'zali the Soulcoiler",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270164,
              name = "Gebbo's Bottomless Bag",
            },
            source = "The Lost Explorers",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270162,
        tier = "S",
        name = "Soulcoiler Ritual Vessel",
        contexts = { "raid" },
      },
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270167,
        tier = "A",
        name = "Wavecaller's Seastone",
        contexts = { "raid" },
      },
      {
        itemId = 250215,
        tier = "A",
        name = "Freightrunner's Flask",
        contexts = { "dungeon" },
      },
      {
        itemId = 250214,
        tier = "A",
        name = "Lightspire Core",
        contexts = { "dungeon" },
      },
      {
        itemId = 270169,
        tier = "A",
        name = "Hex Lord's Dooming Idol",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "B",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 248583,
        tier = "B",
        name = "Drum of Renewed Bonds",
        contexts = { "delves" },
      },
      {
        itemId = 251792,
        tier = "B",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 273649,
        tier = "B",
        name = "Stormbound Emblem of Dazar",
        contexts = { "dungeon" },
      },
      {
        itemId = 250248,
        tier = "B",
        name = "Mycolic Medicine",
        contexts = { "dungeon" },
      },
      {
        itemId = 241340,
        tier = "B",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 245829,
        tier = "B",
        name = "Darkmoon Deck: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 250254,
        tier = "C",
        name = "Seed of Radiant Hope",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "C",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250255,
        tier = "C",
        name = "Unstable Felheart Crystal",
        contexts = { "dungeon" },
      },
      {
        itemId = 270171,
        tier = "D",
        name = "Preternatural Antivenom",
        contexts = { "raid" },
      },
      {
        itemId = 193748,
        tier = "D",
        name = "Kyrakka's Searing Embers",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      flask = {
        itemId = 241322,
        name = "Flask of the Magisters",
      },
      combatPotion = {
        itemId = 241288,
        name = "Potion of Recklessness",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 244031,
          name = "Enchant Weapon - Arcane Mastery",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 244021,
          name = "Enchant Shoulders - Silvermoon's Mending",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 244003,
          name = "Enchant Chest - Mark of the Magister",
        },
      },
      {
        slot = "Helmet",
        best = {
          itemId = 243951,
          name = "Enchant Helm - Empowered Hex of Leeching",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 240155,
          name = "Arcanoweave Spellthread",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243983,
          name = "Enchant Boots - Shaladrassil's Roots",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243959,
          name = "Enchant Ring - Zul'jin's Mastery",
        },
      },
      {
        slot = "Eversong Diamond",
        best = {
          itemId = 240969,
          name = "Telluric Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240900,
          name = "Flawless Quick Amethyst",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241322,
          name = "Flask of the Magisters",
        },
      },
      {
        slot = "Stats Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Mana Potion",
        best = {
          itemId = 241300,
          name = "Lightfused Mana Potion",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 275264,
          name = "Amani Cornucopia",
        },
      },
    },
  },
  ["protection"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268209,
              name = "Aman'muso, Warlord's Vengeance",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Shield",
            item = {
              itemId = 268196,
              name = "Venom-Slashed Scuteward",
            },
            source = "The Lost Explorers",
          },
          {
            slot = "Head",
            item = {
              itemId = 271465,
              name = "Warhelm of the Consecrated Flame",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271463,
              name = "Pauldrons of the Consecrated Flame",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271468,
              name = "Bulwark of the Consecrated Flame",
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            source = "Crafting Blacksmithing",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271466,
              name = "Gauntlets of the Consecrated Flame",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271878,
              name = "Chausses of Unbound Rancor",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 237828,
              name = "Spellbreaker's March",
            },
            source = "Crafting Blacksmithing",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268252,
              name = "Apex Brute's Claw Ring",
            },
            source = "Sszorak",
          },
          {
            slot = "Ring 2",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket 2",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "S",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 270168,
        tier = "S",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "A",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
      {
        itemId = 273797,
        tier = "A",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 158367,
        tier = "A",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 250228,
        tier = "B",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "B",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "B",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "B",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 246304,
        tier = "C",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 246305,
        tier = "C",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 246306,
        tier = "C",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 246307,
        tier = "C",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "C",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 250238,
        tier = "C",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "C",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "D",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250245,
        tier = "D",
        name = "Tumor of the Swarm",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      combatPotion = {
        itemId = 241308,
        name = "Light's Potential",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 243973,
          name = "Enchant Weapon - Berserker's Rage",
        },
      },
      {
        slot = "Shoulder",
        best = {
          itemId = 243963,
          name = "Enchant Shoulders - Akil'zon's Swiftness",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 243981,
          name = "Enchant Helm - Empowered Blessing of Speed",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 244009,
          name = "Enchant Boots - Farstrider's Hunt",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 244015,
          name = "Enchant Ring - Silvermoon's Alacrity",
        },
      },
      {
        slot = "Algari Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240894,
          name = "Flawless Versatile Peridot",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241292,
          name = "Draught of Rampant Abandon",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255845,
          name = "Silvermoon Parade",
        },
      },
    },
  },
  ["retribution"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268213,
              name = "Maze-roa, Warlord's Fury",
              bonusIDs = { 13848 },
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Head",
            item = {
              itemId = 271465,
              name = "Warhelm of the Consecrated Flame",
              bonusIDs = { 12854 },
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
              bonusIDs = { 13848, 13708 },
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271463,
              name = "Pauldrons of the Consecrated Flame",
              bonusIDs = { 12854 },
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
              bonusIDs = { 13848 },
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271468,
              name = "Bulwark of the Consecrated Flame",
              bonusIDs = { 13848 },
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
              bonusIDs = { 13751, 12497, 13836, 8790, 13454 },
            },
            source = "Blacksmithing",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271466,
              name = "Gauntlets of the Consecrated Flame",
              bonusIDs = { 12854 },
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
              bonusIDs = { 13848 },
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271464,
              name = "Greaves of the Consecrated Flame",
              bonusIDs = { 13848, 13846 },
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268260,
              name = "Scaled Fiend's Warboots",
              bonusIDs = { 12854 },
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
              bonusIDs = { 12854 },
            },
            source = "Voidscar Arena",
          },
          {
            slot = "Ring",
            item = {
              itemId = 251513,
              name = "Loa Worshiper's Band",
              bonusIDs = { 13751, 12497, 13836 },
            },
            source = "Jewelcrafting",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
              bonusIDs = { 13848 },
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
              bonusIDs = { 13848 },
            },
            source = "Ula'tek",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "A",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 270164,
        tier = "B",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "B",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "B",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "B",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 251792,
        tier = "B",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 274493,
        tier = "B",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 250228,
        tier = "C",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 158367,
        tier = "C",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "C",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 250238,
        tier = "C",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 273797,
        tier = "C",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 250245,
        tier = "C",
        name = "Tumor of the Swarm",
        contexts = { "dungeon" },
      },
      {
        itemId = 246304,
        tier = "C",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 246305,
        tier = "C",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 270168,
        tier = "D",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 270163,
        tier = "D",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
      {
        itemId = 273795,
        tier = "D",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "D",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 246307,
        tier = "D",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 246306,
        tier = "D",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "D",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
    },
    consumables = {
      flask = {
        itemId = 241322,
        name = "Flask of the Magisters",
      },
      food = {
        itemId = 242275,
        name = "Royal Roast",
      },
      combatPotion = {
        itemId = 241288,
        name = "Potion of Recklessness",
      },
      weaponBuff = {
        itemId = 243733,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 244031,
          name = "Enchant Weapon - Arcane Mastery",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 244007,
          name = "Enchant Helm - Empowered Rune of Avoidance",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 243990,
          name = "Enchant Shoulders - Amirdrassil's Grace",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243952,
          name = "Enchant Boots - Lynx's Dexterity",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Eversong Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240892,
          name = "Flawless Masterful Peridot",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241322,
          name = "Flask of the Magisters",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271883,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 242275,
          name = "Royal Roast",
        },
      },
    },
  },
}
