-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexCraftingData = ClassCodexCraftingData or {}
ClassCodexCraftingData["WARLOCK"] = {
  ["affliction"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 239654,
          name = "Martyr's Slippers",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239671,
          name = "Courtly Wrists",
        },
        {
          itemId = 239652,
          name = "Martyr's Crown",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239672,
          name = "Courtly Robes",
        },
        {
          itemId = 239654,
          name = "Martyr's Slippers",
        },
        {
          itemId = 245768,
          name = "Rootwarden's Lamp",
        },
        {
          itemId = 239671,
          name = "Courtly Wrists",
        },
        {
          itemId = 239653,
          name = "Martyr's Gloves",
        },
        {
          itemId = 239676,
          name = "Courtly Pants",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 239660,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
      },
    },
  },
  ["demonology"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 239654,
          name = "Martyr's Slippers",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239671,
          name = "Courtly Wrists",
        },
        {
          itemId = 239652,
          name = "Martyr's Crown",
        },
        {
          itemId = 239653,
          name = "Martyr's Gloves",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 239654,
          name = "Martyr's Slippers",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 239671,
          name = "Courtly Wrists",
        },
        {
          itemId = 239653,
          name = "Martyr's Gloves",
        },
        {
          itemId = 239651,
          name = "Martyr's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
      },
    },
  },
  ["destruction"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 239654,
          name = "Martyr's Slippers",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 239648,
          name = "Martyr's Bindings",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 239649,
          name = "Martyr's Waistwrap",
          bis = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 239671,
          name = "Courtly Wrists",
        },
        {
          itemId = 239650,
          name = "Martyr's Mantle",
        },
        {
          itemId = 239653,
          name = "Martyr's Gloves",
        },
        {
          itemId = 239652,
          name = "Martyr's Crown",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 239660,
          name = "&nbsp;",
        },
        {
          itemId = 239664,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
      },
    },
  },
}
