-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["WARLOCK"] = {
  affliction = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 250042,
              name = "Abyssal Immolator's Smoldering Flames",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271549,
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 271547,
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 250144,
              name = "Emberwing Feather",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 273778,
              name = "Polished Lightwood Channeler",
            },
          },
          {
            item = {
              itemId = 249276,
              name = "Grimoire of the Eternal Light",
            },
          },
          {
            item = {
              itemId = 271546,
              name = "Skull of the Damned Necrolyte",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271549,
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 250043,
              name = "Abyssal Immolator's Grasps",
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 250144,
              name = "Emberwing Feather",
            },
          },
        },
      },
    },
  },
  demonology = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 250042,
              name = "Abyssal Immolator's Smoldering Flames",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271549,
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 271547,
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 250144,
              name = "Emberwing Feather",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 271546,
              name = "Skull of the Damned Necrolyte",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271549,
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 250043,
              name = "Abyssal Immolator's Grasps",
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 250144,
              name = "Emberwing Feather",
            },
          },
        },
      },
    },
  },
  destruction = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 271546,
              name = "Skull of the Damned Necrolyte",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 250045,
              name = "Abyssal Immolator's Dreadrobe",
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 271547,
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 250144,
              name = "Emberwing Feather",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 271546,
              name = "Skull of the Damned Necrolyte",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271544,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 250045,
              name = "Abyssal Immolator's Dreadrobe",
            },
          },
          {
            item = {
              itemId = 239648,
            },
          },
          {
            item = {
              itemId = 271547,
            },
          },
          {
            item = {
              itemId = 250039,
              name = "Abyssal Immolator's Blazing Core",
            },
          },
          {
            item = {
              itemId = 271545,
            },
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
}
