-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonStats = ClassCodexArchonStats or {}
ClassCodexArchonStats["MONK"] = {
  ["brewmaster"] = {
    ["Mythic+"] = {
      targets = {
        crit = 986,
        haste = 350,
        mastery = 617,
        versatility = 536,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 1157,
        haste = 314,
        mastery = 626,
        versatility = 544,
      },
    },
  },
  ["mistweaver"] = {
    ["Mythic+"] = {
      targets = {
        crit = 783,
        haste = 1137,
        mastery = 352,
        versatility = 246,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 827,
        haste = 1332,
        mastery = 257,
        versatility = 176,
      },
    },
  },
  ["windwalker"] = {
    ["Mythic+"] = {
      targets = {
        crit = 773,
        haste = 884,
        mastery = 745,
        versatility = 201,
      },
    },
    ["Raid"] = {
      targets = {
        crit = 769,
        haste = 904,
        mastery = 833,
        versatility = 167,
      },
    },
  },
}
