-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: murlok.io
ClassCodexMurlokPvp = ClassCodexMurlokPvp or {}
ClassCodexMurlokPvp["MONK"] = {
  ["mistweaver"] = {
    statPriority = {
      {
        key = "versatility",
        rating = 1094,
      },
      {
        key = "haste",
        rating = 698,
      },
      {
        key = "mastery",
        rating = 256,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 239678,
        },
        {
          itemId = 270539,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 244559,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 240155,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 255610,
        },
        {
          itemId = 270532,
        },
      },
      Prismatic = {
        {
          itemId = 240916,
        },
        {
          itemId = 241143,
        },
        {
          itemId = 240870,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 255328,
        },
        {
          itemId = 255616,
        },
        {
          itemId = 280097,
        },
      },
      Waist = {
        {
          itemId = 255467,
        },
        {
          itemId = 244557,
        },
      },
      Wrist = {
        {
          itemId = 244740,
        },
        {
          itemId = 270500,
        },
      },
    },
  },
  ["windwalker"] = {
    statPriority = {
      {
        key = "versatility",
        rating = 1086,
      },
      {
        key = "mastery",
        rating = 1046,
      },
      {
        key = "haste",
        rating = 102,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 239678,
        },
        {
          itemId = 270539,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 271520,
        },
        {
          itemId = 270511,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 240952,
        },
        {
          itemId = 270532,
        },
      },
      Prismatic = {
        {
          itemId = 240902,
        },
        {
          itemId = 241144,
        },
        {
          itemId = 240918,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270559,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 270503,
        },
        {
          itemId = 244557,
        },
      },
      Wrist = {
        {
          itemId = 270500,
        },
        {
          itemId = 244740,
        },
        {
          itemId = 244560,
        },
      },
    },
  },
}
