-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonData = ClassCodexArchonData or {}
ClassCodexArchonData["WARRIOR"] = {
  ["arms"] = {
    label = "Arms Warrior",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:nymrissa",
      "raid:normal:the-coiled-altar",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMbmZmZGmxMDAAAAgxyMDMhxy2AbgBMDTgZwGYmhhBzyMbDwMDAmhBA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCMD2AzM2GbDsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMWmZmZGMmZAAAAAMWmZgJMW2GYBMgZYCMD2AzMM2GMLzsNAzMAYGGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCMD2AzM2GbDsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGzMWmZmZGMmZAAAAAMWmZgJMW2GYBMgZYCMD2AzMM2GMLzsNAzMAYGGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCMD2AzM2GbDsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZAhxyyALgBMDTgZwGYmx2YbglZWGgZGAMDDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphZGzMWmZmZGMmZAAAAAMzyMDMhxy2ALgBMDTgZwGYmhx2ALzsNAzMAYGGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmxyMzMzgxMDAAAAgxyMDMhxy2ALgBMDTgZwGYmx2YbwsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
      ["raid:normal:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCMD2AzM2GbDsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCMD2AzM2GbDsMz2AMzAgZYA",
            recommended = true,
          },
        },
      },
    },
  },
  ["fury"] = {
    label = "Fury Warrior",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:nymrissa",
      "raid:normal:the-coiled-altar",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMz2yMzMzMzMmZmZmZMzyMGzMmNzMzAAAxYZbgFwAmhJwMsBMzwAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMz2yMzMzMzMmZmZmZMzyMGzMmNzMzAAAxYZbgFwAmhJwMsBMzwAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMz2yMzMzMzMmZmZmZMzyMGzMmNzMzAAAxYZbgFwAmhJwMsBMzwAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZmZMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzAAAMzwYWGYwYA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzMzsMzMmZmZzYmBAAixy2ALgBMDTgZYDYmhxGAAMzwYMMGMG",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:normal:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Slayer",
            exportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgBMDTgZYDYmZzYDAAmZYMLDjBjB",
            recommended = true,
          },
        },
      },
    },
  },
  ["protection"] = {
    label = "Protection Warrior",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:the-coiled-altar",
      "raid:heroic:nymrissa",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAjZGzMzYGzmZmlZMGjGzYGLzMzMDzYmBAAAALDAzYAGYD2WMaMDgZBzsBzMmBzCAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMjZmZmZGzixsMMGjGmZstMzMzMMMzAAAAglxAMjBYgNYbxoxMAmNMzGMjZGGAgZGAAmBGD",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAAkBAAmZGzMzMzMmFzMLDjxohxYbZmZmZMDzMAAAAYZmBYGDwAbw2iRjZAMbYmNYYmBDAYmBAgZgxA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Mountain Thane",
            exportString = "CkEAAAAAAAAAAAAAAAAAAAAAA0yAAAzMzYmZGzY2MzsMjxYmGmZYZMzMDzYmBAAAAbDAzYAGYD2WMaMDgZDzsBzYmBzGAMzAAwAGD",
            recommended = true,
          },
        },
      },
    },
  },
}
