-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: wowhead.com
ClassCodexGearData = ClassCodexGearData or {}
ClassCodexGearData["WARRIOR"] = {
  ["arms"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Helm",
            item = {
              itemId = 271456,
              name = "Tempered Horns of the Jade Warlord",
            },
            source = "The Twin Fangs",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271454,
              name = "Raging Pauldrons of the Jade Warlord",
            },
            source = "BoE Trash Drop",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271459,
              name = "Cuirass of the Jade Warlord",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Bracers",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
              bonusIDs = { 12066, 13622, 9627, 8791, 8960, 13767 },
            },
            source = "Crafted",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271457,
              name = "Jeweled Gauntlets of the Jade Warlord",
            },
            source = "Entombed Sentinels",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271455,
              name = "Greaves of the Jade Warlord",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 237828,
              name = "Spellbreaker's March",
              bonusIDs = { 12066, 13622, 9627, 8791, 8960, 13767 },
            },
            source = "Crafted",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
            },
            source = "Voidscar Arena",
          },
          {
            slot = "Ring",
            item = {
              itemId = 273792,
              name = "Band of the Amani Warlord",
            },
            source = "Altar of Fangs",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
          {
            slot = "Mainhand",
            item = {
              itemId = 268213,
              name = "Maze-roa, Warlord's Fury",
            },
            source = "The Coiled Altar",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "dungeon" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "raid" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250228,
        tier = "A",
        name = "Resonant Bellowstone",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "A",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 250238,
        tier = "B",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "B",
        name = "Idol of the War Loa",
        contexts = { "raid" },
      },
      {
        itemId = 193757,
        tier = "B",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "B",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 270168,
        tier = "C",
        name = "Font of Venomous Rage",
        contexts = { "dungeon" },
      },
      {
        itemId = 273797,
        tier = "C",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "C",
        name = "Sszorak's Ferocity",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "C",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      combatPotion = {
        itemId = 241288,
        name = "Potion of Recklessness",
      },
      food = {
        itemId = 255846,
        name = "Harandar Celebration",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 243973,
          name = "Enchant Weapon - Berserker's Rage",
        },
      },
      {
        slot = "Helm",
        best = {
          itemId = 243951,
          name = "Enchant Helm - Empowered Hex of Leeching",
        },
      },
      {
        slot = "Shoulder",
        best = {
          itemId = 243991,
          name = "Enchant Shoulders - Amirdrassil's Grace",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244643,
          name = "Blood Knight's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243953,
          name = "Enchant Boots - Lynx's Dexterity",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Diamond",
        best = {
          itemId = 240967,
          name = "Powerful Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240906,
          name = "Flawless Quick Garnet",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 242273,
          name = "Blooming Feast",
        },
      },
    },
  },
  ["fury"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Helm",
            item = {
              itemId = 271456,
              name = "Tempered Horns of the Jade Warlord",
            },
            source = "Murder Row",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271454,
              name = "Raging Pauldrons of the Jade Warlord",
            },
            source = "Murder Row",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271459,
              name = "Cuirass of the Jade Warlord",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Bracers",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
              bonusIDs = { 12066, 13622, 9627, 8793, 8960, 13767 },
            },
            source = "Crafted",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271457,
              name = "Jeweled Gauntlets of the Jade Warlord",
            },
            source = "Den of Nalorakk",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271455,
              name = "Greaves of the Jade Warlord",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268260,
              name = "Scaled Fiend's Warboots",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 252258,
              name = "Sickening Signet of Atroxus",
            },
            source = "Voidscar Arena",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
          {
            slot = "Mainhand",
            item = {
              itemId = 268213,
              name = "Maze-roa, Warlord's Fury",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Offhand",
            item = {
              itemId = 237846,
              name = "Blood Knight's Warblade",
              bonusIDs = { 13751, 12497, 13836, 13771, 8793 },
            },
            source = "Crafted",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "dungeon" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "raid" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250228,
        tier = "A",
        name = "Resonant Bellowstone",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "A",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 250238,
        tier = "B",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "B",
        name = "Idol of the War Loa",
        contexts = { "raid" },
      },
      {
        itemId = 193757,
        tier = "B",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "B",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 270168,
        tier = "C",
        name = "Font of Venomous Rage",
        contexts = { "dungeon" },
      },
      {
        itemId = 273797,
        tier = "C",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "C",
        name = "Sszorak's Ferocity",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "C",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      combatPotion = {
        itemId = 241288,
        name = "Potion of Recklessness",
      },
      food = {
        itemId = 255846,
        name = "Harandar Celebration",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 243973,
          name = "Enchant Weapon - Berserker's Rage",
        },
      },
      {
        slot = "Helm",
        best = {
          itemId = 243951,
          name = "Enchant Helm - Empowered Hex of Leeching",
        },
      },
      {
        slot = "Shoulder",
        best = {
          itemId = 243991,
          name = "Enchant Shoulders - Amirdrassil's Grace",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244643,
          name = "Blood Knight's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243953,
          name = "Enchant Boots - Lynx's Dexterity",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243959,
          name = "Enchant Ring - Zul'jin's Mastery",
        },
      },
      {
        slot = "Diamond",
        best = {
          itemId = 240967,
          name = "Powerful Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240900,
          name = "Flawless Quick Amethyst",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241288,
          name = "Potion of Recklessness",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 242273,
          name = "Blooming Feast",
        },
      },
    },
  },
  ["protection"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 268209,
              name = "Aman'muso, Warlord's Vengeance",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Shield",
            item = {
              itemId = 268196,
              name = "Venom-Slashed Scuteward",
            },
            source = "The Lost Explorers",
          },
          {
            slot = "Head",
            item = {
              itemId = 271456,
              name = "Tempered Horns of the Jade Warlord",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271454,
              name = "Raging Pauldrons of the Jade Warlord",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271459,
              name = "Cuirass of the Jade Warlord",
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 237834,
              name = "Spellbreaker's Bracers",
            },
            source = "Crafting Blacksmithing",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271457,
              name = "Jeweled Gauntlets of the Jade Warlord",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268259,
              name = "Girdle of Toxic Regret",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271878,
              name = "Chausses of Unbound Rancor",
            },
            source = "Ula'tek",
          },
          {
            slot = "Boots",
            item = {
              itemId = 237828,
              name = "Spellbreaker's March",
            },
            source = "Crafting Blacksmithing",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268252,
              name = "Apex Brute's Claw Ring",
            },
            source = "Sszorak",
          },
          {
            slot = "Ring 2",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270173,
              name = "Zul'jin's Guillotine Technique",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Trinket 2",
            item = {
              itemId = 270175,
              name = "Voracious Heart of Ula'tek",
            },
            source = "Ula'tek",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270173,
        tier = "S",
        name = "Zul'jin's Guillotine Technique",
        contexts = { "raid" },
      },
      {
        itemId = 270175,
        tier = "S",
        name = "Voracious Heart of Ula'tek",
        contexts = { "raid" },
      },
      {
        itemId = 270165,
        tier = "S",
        name = "Keeper's Seething Core",
        contexts = { "raid" },
      },
      {
        itemId = 270168,
        tier = "S",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 270163,
        tier = "A",
        name = "Sszorak's Ferocity",
        contexts = { "raid" },
      },
      {
        itemId = 273797,
        tier = "A",
        name = "Tattered Amani War Banner",
        contexts = { "dungeon" },
      },
      {
        itemId = 158367,
        tier = "A",
        name = "Merektha's Fang",
        contexts = { "dungeon" },
      },
      {
        itemId = 250228,
        tier = "B",
        name = "Resonant Bellowstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 273795,
        tier = "B",
        name = "Coiled Fangstone",
        contexts = { "dungeon" },
      },
      {
        itemId = 250229,
        tier = "B",
        name = "Idol of the War Loa",
        contexts = { "dungeon" },
      },
      {
        itemId = 193762,
        tier = "B",
        name = "Blazebinder's Hoof",
        contexts = { "dungeon" },
      },
      {
        itemId = 246304,
        tier = "C",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 246305,
        tier = "C",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 246306,
        tier = "C",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 246307,
        tier = "C",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "C",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 250238,
        tier = "C",
        name = "Seed of the Devouring Wild",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "C",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "D",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250245,
        tier = "D",
        name = "Tumor of the Swarm",
        contexts = { "dungeon" },
      },
    },
    consumables = {
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      combatPotion = {
        itemId = 241308,
        name = "Light's Potential",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 243973,
          name = "Enchant Weapon - Berserker's Rage",
        },
      },
      {
        slot = "Shoulder",
        best = {
          itemId = 243963,
          name = "Enchant Shoulders - Akil'zon's Swiftness",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 243981,
          name = "Enchant Helm - Empowered Blessing of Speed",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 244641,
          name = "Forest Hunter's Armor Kit",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 244009,
          name = "Enchant Boots - Farstrider's Hunt",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 244015,
          name = "Enchant Ring - Silvermoon's Alacrity",
        },
      },
      {
        slot = "Algari Diamond",
        best = {
          itemId = 240983,
          name = "Indecipherable Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240894,
          name = "Flawless Versatile Peridot",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241292,
          name = "Draught of Rampant Abandon",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255845,
          name = "Silvermoon Parade",
        },
      },
    },
  },
}
