-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonStats = ClassCodexArchonStats or {}
ClassCodexArchonStats["MAGE"] = {
  arcane = {
    ["Mythic+"] = {
      targets = {
        crit = 687,
        haste = 886,
        mastery = 682,
        versatility = 247,
      },
    },
    Raid = {
      targets = {
        crit = 682,
        haste = 972,
        mastery = 717,
        versatility = 240,
      },
    },
  },
  fire = {
    ["Mythic+"] = {
      targets = {
        crit = 226,
        haste = 1217,
        mastery = 892,
        versatility = 186,
      },
    },
    Raid = {
      targets = {
        crit = 218,
        haste = 1305,
        mastery = 897,
        versatility = 151,
      },
    },
  },
  frost = {
    ["Mythic+"] = {
      targets = {
        crit = 918,
        haste = 681,
        mastery = 937,
        versatility = 140,
      },
    },
    Raid = {
      targets = {
        crit = 922,
        haste = 705,
        mastery = 928,
        versatility = 126,
      },
    },
  },
}
