-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: wowhead.com
ClassCodexGearData = ClassCodexGearData or {}
ClassCodexGearData["MAGE"] = {
  ["arcane"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 271092,
              name = "Jan'thrazet, the Soul Fang",
            },
            source = "Ula'tek",
          },
          {
            slot = "Offhand",
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
            source = "Crafting",
          },
          {
            slot = "Head",
            item = {
              itemId = 271564,
              name = "Crown of the Primal Leywarden",
            },
            source = "Ula'tek",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271562,
              name = "Primal Leywarden's Manaflux",
            },
            source = "The Twin Fangs",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271567,
              name = "Crest of the Primal Leywarden",
            },
            source = "Altar of Fangs",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            source = "Crafting",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271565,
              name = "Primal Leywarden's Manashapers",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268257,
              name = "Caustic Chain-Wrapped Sash",
            },
            source = "Sszorak",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271563,
              name = "Primal Leywarden's Tailored Legwraps",
            },
            source = "Nek'zali the Soulcoiler",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268255,
              name = "Cackling Soultreads",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268266,
              name = "Alluring Bubbleband",
            },
            source = "Nymrissa Wavecaller",
          },
          {
            slot = "Ring",
            item = {
              itemId = 251148,
              name = "Pilfered Precious Band",
            },
            source = "Den of Nalorakk",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 250215,
              name = "Freightrunner's Flask",
            },
            source = "Murder Row",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270164,
              name = "Gebbo's Bottomless Bag",
            },
            source = "The Lost Explorers",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 250215,
        tier = "A+",
        name = "Freightrunner's Flask",
        contexts = { "dungeon" },
      },
      {
        itemId = 270167,
        tier = "A+",
        name = "Wavecaller's Seastone",
        contexts = { "raid" },
      },
      {
        itemId = 250214,
        tier = "A",
        name = "Lightspire Core",
        contexts = { "dungeon" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 250224,
        tier = "A",
        name = "Mindpiercer's Sigil",
        contexts = { "dungeon" },
      },
      {
        itemId = 251792,
        tier = "A",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 270170,
        tier = "B",
        name = "Vexhul's Everflowing Gland",
        contexts = { "raid" },
      },
      {
        itemId = 270169,
        tier = "B",
        name = "Hex Lord's Dooming Idol",
        contexts = { "raid" },
      },
      {
        itemId = 273649,
        tier = "B",
        name = "Stormbound Emblem of Dazar",
        contexts = { "dungeon" },
      },
      {
        itemId = 250259,
        tier = "B",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 273794,
        tier = "B",
        name = "Knot of Writhing Serpents",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "B",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 270161,
        tier = "B",
        name = "Fang of Umbral Malignance",
        contexts = { "raid" },
      },
      {
        itemId = 270603,
        tier = "C",
        name = "Venomous Gladiator's Insignia of Alacrity",
        contexts = { "delves" },
      },
      {
        itemId = 251785,
        tier = "C",
        name = "Void-Reaper's Libram",
        contexts = { "delves" },
      },
      {
        itemId = 251784,
        tier = "C",
        name = "Sylvan Wakrapuku",
        contexts = { "delves" },
      },
      {
        itemId = 264878,
        tier = "C",
        name = "Astalor's Anguish Agitator",
        contexts = { "delves" },
      },
      {
        itemId = 270602,
        tier = "C",
        name = "Venomous Gladiator's Badge of Ferocity",
        contexts = { "delves" },
      },
      {
        itemId = 250462,
        tier = "F",
        name = "Forgotten Farstrider's Insignia",
        contexts = { "delves" },
      },
      {
        itemId = 270168,
        tier = "F",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 251786,
        tier = "F",
        name = "Ever-Collapsing Void Fissure",
        contexts = { "delves" },
      },
      {
        itemId = 251783,
        tier = "F",
        name = "Lost Idol of the Hash'ey",
        contexts = { "delves" },
      },
      {
        itemId = 251787,
        tier = "F",
        name = "Sealed Chaos Urn",
        contexts = { "delves" },
      },
      {
        itemId = 274493,
        tier = "F",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 274496,
        tier = "F",
        name = "Ophidian Bone Whistle",
        contexts = { "delves" },
      },
      {
        itemId = 274497,
        tier = "F",
        name = "Spirit-Rending Poison",
        contexts = { "delves" },
      },
      {
        itemId = 246305,
        tier = "F",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 246304,
        tier = "F",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 246306,
        tier = "F",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 246307,
        tier = "F",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "F",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
    },
    consumables = {
      flask = {
        itemId = 241324,
        name = "Flask of the Blood Knights",
      },
      combatPotion = {
        itemId = 241308,
        name = "Light's Potential",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
      food = {
        itemId = 255845,
        name = "Silvermoon Parade",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 244029,
          name = "Enchant Weapon - Acuity of the Ren'dorei",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 244007,
          name = "Enchant Helm - Empowered Rune of Avoidance",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 244021,
          name = "Enchant Shoulders - Silvermoon's Mending",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 240155,
          name = "Arcanoweave Spellthread",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243983,
          name = "Enchant Boots - Shaladrassil's Roots",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Eversong Diamond",
        best = {
          itemId = 240967,
          name = "Powerful Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240900,
          name = "Flawless Quick Amethyst",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241324,
          name = "Flask of the Blood Knights",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241308,
          name = "Light's Potential",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255845,
          name = "Silvermoon Parade",
        },
      },
    },
  },
  ["fire"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Offhand",
            item = {
              itemId = 159667,
              name = "Vessel of Last Rites",
            },
            source = "King's Rest",
          },
          {
            slot = "Belt",
            item = {
              itemId = 239649,
              name = "Martyr's Waistwrap",
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Weapon",
            item = {
              itemId = 271092,
              name = "Jan'thrazet, the Soul Fang",
            },
            source = "Ula'tek",
          },
          {
            slot = "Offhand",
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
            source = "Crafting",
          },
          {
            slot = "Head",
            item = {
              itemId = 271564,
              name = "Crown of the Primal Leywarden",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 251142,
              name = "Pendant of Malefic Fury",
            },
            source = "Murder Row",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271562,
              name = "Primal Leywarden's Manaflux",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271567,
              name = "Crest of the Primal Leywarden",
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271565,
              name = "Primal Leywarden's Manashapers",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 268257,
              name = "Caustic Chain-Wrapped Sash",
            },
            source = "Sszorak",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271563,
              name = "Primal Leywarden's Tailored Legwraps",
            },
            source = "Tier Set",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268255,
              name = "Cackling Soultreads",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268266,
              name = "Alluring Bubbleband",
            },
            source = "Nymrissa Wavecaller",
          },
          {
            slot = "Ring",
            item = {
              itemId = 159459,
              name = "Ritual Binder's Ring",
            },
            source = "King's Rest",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 273796,
              name = "Vile Vial of Volatile Venom",
            },
            source = "Altar of Fangs",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270164,
              name = "Gebbo's Bottomless Bag",
            },
            source = "The Lost Explorers",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "S",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 270167,
        tier = "S",
        name = "Wavecaller's Seastone",
        contexts = { "raid" },
      },
      {
        itemId = 250214,
        tier = "A",
        name = "Lightspire Core",
        contexts = { "dungeon" },
      },
      {
        itemId = 270170,
        tier = "A",
        name = "Vexhul's Everflowing Gland",
        contexts = { "raid" },
      },
      {
        itemId = 250259,
        tier = "A",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 250224,
        tier = "B",
        name = "Mindpiercer's Sigil",
        contexts = { "dungeon" },
      },
      {
        itemId = 270169,
        tier = "B",
        name = "Hex Lord's Dooming Idol",
        contexts = { "raid" },
      },
      {
        itemId = 273649,
        tier = "B",
        name = "Stormbound Emblem of Dazar",
        contexts = { "dungeon" },
      },
      {
        itemId = 270161,
        tier = "C",
        name = "Fang of Umbral Malignance",
        contexts = { "raid" },
      },
      {
        itemId = 270168,
        tier = "C",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 273794,
        tier = "C",
        name = "Knot of Writhing Serpents",
        contexts = { "dungeon" },
      },
      {
        itemId = 274493,
        tier = "C",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 251792,
        tier = "C",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 193757,
        tier = "D",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250215,
        tier = "D",
        name = "Freightrunner's Flask",
        contexts = { "dungeon" },
      },
      {
        itemId = 246305,
        tier = "D",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 246304,
        tier = "D",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 246306,
        tier = "D",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 246307,
        tier = "D",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "D",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 251786,
        tier = "D",
        name = "Ever-Collapsing Void Fissure",
        contexts = { "delves" },
      },
      {
        itemId = 274497,
        tier = "D",
        name = "Spirit-Rending Poison",
        contexts = { "delves" },
      },
      {
        itemId = 274496,
        tier = "D",
        name = "Ophidian Bone Whistle",
        contexts = { "delves" },
      },
      {
        itemId = 250462,
        tier = "D",
        name = "Forgotten Farstrider's Insignia",
        contexts = { "delves" },
      },
      {
        itemId = 251783,
        tier = "D",
        name = "Lost Idol of the Hash'ey",
        contexts = { "delves" },
      },
      {
        itemId = 251787,
        tier = "D",
        name = "Sealed Chaos Urn",
        contexts = { "delves" },
      },
      {
        itemId = 251784,
        tier = "D",
        name = "Sylvan Wakrapuku",
        contexts = { "delves" },
      },
      {
        itemId = 251785,
        tier = "D",
        name = "Void-Reaper's Libram",
        contexts = { "delves" },
      },
      {
        itemId = 280123,
        tier = "D",
        name = "Sharp Axe Holster",
        contexts = { "delves" },
      },
      {
        itemId = 274496,
        tier = "D",
        name = "Ophidian Bone Whistle",
        contexts = { "delves" },
      },
    },
    consumables = {
      flask = {
        itemId = 241322,
        name = "Flask of the Magisters",
      },
      combatPotion = {
        itemId = 241308,
        name = "Light's Potential",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
      food = {
        itemId = 242272,
        name = "Quel'dorei Medley",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 244029,
          name = "Enchant Weapon - Acuity of the Ren'dorei",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 244007,
          name = "Enchant Helm - Empowered Rune of Avoidance",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 243991,
          name = "Enchant Shoulders - Amirdrassil's Grace",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 240133,
          name = "Sunfire Silk Spellthread",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243953,
          name = "Enchant Boots - Lynx's Dexterity",
        },
      },
      {
        slot = "Rings",
        best = {
          itemId = 243957,
          name = "Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241322,
          name = "Flask of the Magisters",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241308,
          name = "Light's Potential",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255846,
          name = "Harandar Celebration",
        },
      },
    },
    gems = {
      primary = {
        itemId = 240967,
        name = "Powerful Eversong Diamond",
      },
      secondary = {
        {
          itemId = 240892,
          name = "Flawless Masterful Peridot",
        },
        {
          itemId = 240900,
          name = "Flawless Quick Amethyst",
        },
        {
          itemId = 240916,
          name = "Flawless Quick Lapis",
        },
      },
    },
  },
  ["frost"] = {
    bisGear = {
      {
        label = "Overall",
        slots = {
          {
            slot = "Weapon",
            item = {
              itemId = 271092,
              name = "Jan'thrazet, the Soul Fang",
            },
            source = "Ula'tek",
          },
          {
            slot = "Offhand",
            item = {
              itemId = 268263,
              name = "Frostscale's Mystic Frond",
            },
            source = "Nymrissa Wavecaller",
          },
          {
            slot = "Head",
            item = {
              itemId = 271564,
              name = "Crown of the Primal Leywarden",
            },
            source = "Tier Set",
          },
          {
            slot = "Neck",
            item = {
              itemId = 268265,
              name = "Aqirbane Reliquary",
            },
            source = "Ula'tek",
          },
          {
            slot = "Shoulders",
            item = {
              itemId = 271562,
              name = "Primal Leywarden's Manaflux",
            },
            source = "Tier Set",
          },
          {
            slot = "Cloak",
            item = {
              itemId = 268253,
              name = "Silken Voodoo Drape",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Chest",
            item = {
              itemId = 271567,
              name = "Crest of the Primal Leywarden",
            },
            source = "Tier Set",
          },
          {
            slot = "Wrist",
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
              bonusIDs = { 8791, 8960, 12214, 12384, 13668, 13751 },
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Gloves",
            item = {
              itemId = 271565,
              name = "Primal Leywarden's Manashapers",
            },
            source = "Tier Set",
          },
          {
            slot = "Belt",
            item = {
              itemId = 239649,
              name = "Martyr's Waistwrap",
              bonusIDs = { 8791, 8960, 12214, 12384, 13668, 13751 },
            },
            source = "Crafting/Misc",
          },
          {
            slot = "Legs",
            item = {
              itemId = 271563,
              name = "Primal Leywarden's Tailored Legwraps",
            },
            source = "Tier Set",
          },
          {
            slot = "Boots",
            item = {
              itemId = 268255,
              name = "Cackling Soultreads",
            },
            source = "The Coiled Altar",
          },
          {
            slot = "Ring",
            item = {
              itemId = 268249,
              name = "Vile Alchemist's Band",
            },
            source = "Vashnik the Malignant",
          },
          {
            slot = "Ring",
            item = {
              itemId = 158366,
              name = "Charged Sandstone Band",
            },
            source = "Temple of Sethraliss",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270164,
              name = "Gebbo's Bottomless Bag",
            },
            source = "The Lost Explorers",
          },
          {
            slot = "Trinket",
            item = {
              itemId = 270167,
              name = "Wavecaller's Seastone",
            },
            source = "Nymrissa Wavecaller",
          },
        },
      },
    },
    trinkets = {
      {
        itemId = 270164,
        tier = "S",
        name = "Gebbo's Bottomless Bag",
        contexts = { "raid" },
      },
      {
        itemId = 270167,
        tier = "S",
        name = "Wavecaller's Seastone",
        contexts = { "raid" },
      },
      {
        itemId = 273796,
        tier = "A",
        name = "Vile Vial of Volatile Venom",
        contexts = { "dungeon" },
      },
      {
        itemId = 273649,
        tier = "A",
        name = "Stormbound Emblem of Dazar",
        contexts = { "dungeon" },
      },
      {
        itemId = 250224,
        tier = "A",
        name = "Mindpiercer's Sigil",
        contexts = { "dungeon" },
      },
      {
        itemId = 250215,
        tier = "A",
        name = "Freightrunner's Flask",
        contexts = { "dungeon" },
      },
      {
        itemId = 270170,
        tier = "A",
        name = "Vexhul's Everflowing Gland",
        contexts = { "raid" },
      },
      {
        itemId = 270168,
        tier = "A",
        name = "Font of Venomous Rage",
        contexts = { "raid" },
      },
      {
        itemId = 250259,
        tier = "B",
        name = "Sapling of the Dawnroot",
        contexts = { "dungeon" },
      },
      {
        itemId = 193757,
        tier = "B",
        name = "Ruby Whelp Shell",
        contexts = { "dungeon" },
      },
      {
        itemId = 250214,
        tier = "B",
        name = "Lightspire Core",
        contexts = { "dungeon" },
      },
      {
        itemId = 270161,
        tier = "B",
        name = "Fang of Umbral Malignance",
        contexts = { "raid" },
      },
      {
        itemId = 270169,
        tier = "B",
        name = "Hex Lord's Dooming Idol",
        contexts = { "raid" },
      },
      {
        itemId = 251792,
        tier = "B",
        name = "Glorious Crusader's Keepsake",
        contexts = { "delves" },
      },
      {
        itemId = 274493,
        tier = "B",
        name = "Effigy of Ula'tek's Faithful",
        contexts = { "delves" },
      },
      {
        itemId = 248583,
        tier = "B",
        name = "Drum of Renewed Bonds",
        contexts = { "delves" },
      },
      {
        itemId = 246305,
        tier = "B",
        name = "Darkmoon Dominion: Blood",
        contexts = { "crafting" },
      },
      {
        itemId = 246304,
        tier = "B",
        name = "Darkmoon Dominion: Hunt",
        contexts = { "crafting" },
      },
      {
        itemId = 273794,
        tier = "C",
        name = "Knot of Writhing Serpents",
        contexts = { "dungeon" },
      },
      {
        itemId = 158368,
        tier = "C",
        name = "Sethraliss' Defiled Relic",
        contexts = { "dungeon" },
      },
      {
        itemId = 246306,
        tier = "C",
        name = "Darkmoon Dominion: Rot",
        contexts = { "crafting" },
      },
      {
        itemId = 246307,
        tier = "C",
        name = "Darkmoon Dominion: Void",
        contexts = { "crafting" },
      },
      {
        itemId = 241340,
        tier = "C",
        name = "Magister's Alchemist Stone",
        contexts = { "crafting" },
      },
      {
        itemId = 251785,
        tier = "C",
        name = "Void-Reaper's Libram",
        contexts = { "delves" },
      },
      {
        itemId = 251784,
        tier = "C",
        name = "Sylvan Wakrapuku",
        contexts = { "delves" },
      },
      {
        itemId = 251786,
        tier = "C",
        name = "Ever-Collapsing Void Fissure",
        contexts = { "delves" },
      },
      {
        itemId = 274496,
        tier = "C",
        name = "Ophidian Bone Whistle",
        contexts = { "delves" },
      },
      {
        itemId = 274497,
        tier = "C",
        name = "Spirit-Rending Poison",
        contexts = { "delves" },
      },
      {
        itemId = 251783,
        tier = "C",
        name = "Lost Idol of the Hash'ey",
        contexts = { "delves" },
      },
    },
    consumables = {
      flask = {
        itemId = 241322,
        name = "Flask of the Magisters",
      },
      combatPotion = {
        itemId = 241308,
        name = "Light's Potential",
      },
      weaponBuff = {
        itemId = 243734,
        name = "Thalassian Phoenix Oil",
      },
    },
    enchants = {
      {
        slot = "Weapon",
        best = {
          itemId = 244029,
          name = "Enchant Weapon - Acuity of the Ren'dorei",
        },
      },
      {
        slot = "Head",
        best = {
          itemId = 244007,
          name = "Enchant Helm - Empowered Rune of Avoidance",
        },
      },
      {
        slot = "Shoulders",
        best = {
          itemId = 243991,
          name = "Enchant Shoulders - Amirdrassil's Grace",
        },
      },
      {
        slot = "Chest",
        best = {
          itemId = 243977,
          name = "Enchant Chest - Mark of the Worldsoul",
        },
      },
      {
        slot = "Legs",
        best = {
          itemId = 240133,
          name = "Sunfire Silk Spellthread",
        },
      },
      {
        slot = "Boots",
        best = {
          itemId = 243953,
          name = "Enchant Boots - Lynx's Dexterity",
        },
      },
      {
        slot = "Ring",
        best = {
          itemId = 256739,
          name = "Formula: Enchant Ring - Eyes of the Eagle",
        },
      },
      {
        slot = "Thalassian Diamond",
        best = {
          itemId = 240967,
          name = "Powerful Eversong Diamond",
        },
      },
      {
        slot = "Other Gems",
        best = {
          itemId = 240898,
          name = "Flawless Deadly Amethyst",
        },
      },
      {
        slot = "Flask",
        best = {
          itemId = 241322,
          name = "Flask of the Magisters",
        },
      },
      {
        slot = "Combat Potion",
        best = {
          itemId = 241308,
          name = "Light's Potential",
        },
      },
      {
        slot = "Health Potion",
        best = {
          itemId = 271884,
          name = "Concentrated Silvermoon Health Potion",
        },
      },
      {
        slot = "Weapon Buff",
        best = {
          itemId = 243734,
          name = "Thalassian Phoenix Oil",
        },
      },
      {
        slot = "Augment Rune",
        best = {
          itemId = 259085,
          name = "Void-Touched Augment Rune",
        },
      },
      {
        slot = "Food",
        best = {
          itemId = 255846,
          name = "Harandar Celebration",
        },
      },
      {
        slot = "Tea",
        best = {
          itemId = 242298,
          name = "Argentleaf Tea",
        },
      },
    },
  },
}
