-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: icy-veins.com
ClassCodexIcyVeinsTalentData = ClassCodexIcyVeinsTalentData or {}
ClassCodexIcyVeinsTalentData["MAGE"] = {
  ["arcane"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Arcane Raid -\nSunfury",
        exportString = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAgNAAAzMDbWmxMLzYMzMzMsxMmZmBAYAAAGgZGwMAYYmZA",
      },
      {
        context = "Mythic+",
        buildLabel = "Arcane Mythic+ -\nSunfury",
        exportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMzAAAwAAmZmmlllZAAsBAwGMzMsZZGzsMjxMzMzwGzYGzAAMAAADwMDMzAghZmB",
      },
      {
        context = "Delves",
        buildLabel = "Arcane Delves -\nSunfury",
        exportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZGzsYzMDNzYGAAADAYmZaWWWmBAwGAAbwMzwmlZMzyMGzMzMDbMjZMDAwAAAMAzMwMDAGmZG",
      },
      {
        context = "Leveling",
        buildLabel = "Arcane Level 80 Midnight Leveling",
        exportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMjFDzYmFegZGamZGAAAGAwMzkFmBAwGAAbwMzwmlZMzyMGzMzMDbMjZMDAwAAAMAzMgZAAGzA",
        leveling = true,
      },
    },
  },
  ["fire"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Fire Raid -\nSunfury",
        exportString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sstMDAwmZmx2MzMzYDAAAAAbmZMzAAgZMmZmZMzsMAMzAMGwMMGA",
      },
      {
        context = "Mythic+",
        buildLabel = "Fire Mythic+ -\nSunfury",
        exportString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsgZGZmZGAAAAAmZmmltlZAA2MzM2mZmZGbAAAAAYzMjZGAAMjxMzMjZmlBgZGMjxAmhxA",
      },
      {
        context = "Leveling",
        buildLabel = "Fire Level 80 Midnight Leveling",
        exportString = "C8DAAAAAAAAAAAAAAAAAAAAAAMjFDzYmFbzMjMzYAAAYAAzMTWYGAgNzMjtxMzM2AAAAAwmZGzAAAjZMzYmZmZBAzMwgxgZAA",
        leveling = true,
      },
    },
  },
  ["frost"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Frost Single Target",
        exportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbbjZmZwsNPgxMsAAAwMbAzADYGMMA",
      },
      {
        context = "Raid",
        buildLabel = "Frost Light Cleave/Raid",
        exportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbbMzMDmthxMsAAAwMbAzADYGMMA",
      },
      {
        context = "General",
        buildLabel = "Frost AoE",
        exportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMWMzMzMzYmlZamZZWAAAgFAAAAAAYBgttxMzMY2mxMzYbBAAAMzgZgBMDwA",
      },
      {
        context = "Leveling",
        buildLabel = "Frost Level 80 Midnight Levelling",
        exportString = "CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmNmZmYmxMzMzMziZmZMmZmlZamZZWAAAgFAAAAAAYBgttxMzMY2mxYGbbAAAgZGMgBAGGA",
        leveling = true,
      },
    },
  },
}
