-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonData = ClassCodexArchonData or {}
ClassCodexArchonData["PRIEST"] = {
  discipline = {
    label = "Discipline Priest",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:the-coiled-altar",
      "raid:heroic:nymrissa",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgxYZGMzMDzwMGmpZiBYmFMEGzyAMGsAAAjZmZMYGgZmBYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgxYZGMzMDGzMGMNTMAzsghwYWGgxgFAAYMzMjhZGgZmBYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAghZbGMzMDGzMYz0MxAMzCGCjZZAGDWAAgZmZmxgZAmZGgZA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMDzYmxgpZiBYmFMEGzyAMGsAAAjZmZMYGgZmBYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMDzwMwMNTMAzsghwYWGgxgFAAYMzMjBzAMzMDYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgxYZGMzMDzYmxgpZiBYmFMEGzyAMGsAAAjZmZMYGgZmBYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgxYZGMzMDzwMGmpZiBYmFMEGzyAMGsAAAjZmZMYGgZmBYG",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMzwYmBbmmJGgZWwQYMLDwYwCAAMmZmxgZAmZGgZA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAghZZGMzMDGzMYz0MxAMzCGCjZZAGDWAAgZmZmxgZAmZGgZA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stBGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Voidweaver",
            exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzwMgpZamBzMAAAz2stAGbGAAGjZGDzMYmBjgB",
            recommended = true,
          },
        },
      },
    },
  },
  holy = {
    label = "Holy Priest",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:nymrissa",
      "raid:normal:the-coiled-altar",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Oracle",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAbGzYWGzMmZMMDsMzMzAAAAYMzyMMzMzYbGzMAmpAYmFMEGz2AMGYxMzAgZMzDYMYGgZmBMA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxMjZmZYmZYZGmBAAAwwsMDzMzMYGzAYmaAgZWMDziBAGD2MzMbAaGmxYYmZbZAmBGA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:normal:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
            recommended = true,
          },
        },
      },
    },
  },
  shadow = {
    label = "Shadow Priest",
    contextOrder = {
      "mythic-plus:10:all-dungeons",
      "mythic-plus:10:altar-of-fangs",
      "mythic-plus:10:den-of-nalorakk",
      "mythic-plus:10:kings-rest",
      "mythic-plus:10:murder-row",
      "mythic-plus:10:ruby-life-pools",
      "mythic-plus:10:sethraliss",
      "mythic-plus:10:the-blinding-vale",
      "mythic-plus:10:voidscar-arena",
      "raid:heroic:all-bosses",
      "raid:heroic:nekzali",
      "raid:heroic:sentinels",
      "raid:heroic:vashnik",
      "raid:heroic:explorers",
      "raid:heroic:sszorak",
      "raid:heroic:the-twin-fangs",
      "raid:heroic:the-coiled-altar",
      "raid:heroic:nymrissa",
      "raid:normal:ulatek",
    },
    contexts = {
      ["mythic-plus:10:all-dungeons"] = {
        zoneType = "mythic-plus",
        encounter = "all-dungeons",
        encounterLabel = "All Dungeons",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGD2mZGzMzYDZGLbz0AMDwMbmhZzAQGjFAMzAGzMzY2YmtlBYGMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:altar-of-fangs"] = {
        zoneType = "mythic-plus",
        encounter = "altar-of-fangs",
        encounterLabel = "Altar of Fangs",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:den-of-nalorakk"] = {
        zoneType = "mythic-plus",
        encounter = "den-of-nalorakk",
        encounterLabel = "Den of Nalorakk",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGDz2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:kings-rest"] = {
        zoneType = "mythic-plus",
        encounter = "kings-rest",
        encounterLabel = "Kings' Rest",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:murder-row"] = {
        zoneType = "mythic-plus",
        encounter = "murder-row",
        encounterLabel = "Murder Row",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGDz2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:ruby-life-pools"] = {
        zoneType = "mythic-plus",
        encounter = "ruby-life-pools",
        encounterLabel = "Ruby Life Pools",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGD2mZGzMzYDZGLbz0AMDwMbmhZzAQGjFAMzAGzMzY2YmtlBYGMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:sethraliss"] = {
        zoneType = "mythic-plus",
        encounter = "sethraliss",
        encounterLabel = "Sethraliss",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:the-blinding-vale"] = {
        zoneType = "mythic-plus",
        encounter = "the-blinding-vale",
        encounterLabel = "The Blinding Vale",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGD2mZGzMzYDZGLbz0AMDwMbmhZzAQGjFAMzAGzMzY2YmtlBYGMA",
            recommended = true,
          },
        },
      },
      ["mythic-plus:10:voidscar-arena"] = {
        zoneType = "mythic-plus",
        encounter = "voidscar-arena",
        encounterLabel = "Voidscar Arena",
        difficulty = "10",
        difficultyLabel = "+7 to +19",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:all-bosses"] = {
        zoneType = "raid",
        encounter = "all-bosses",
        encounterLabel = "All Bosses",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nekzali"] = {
        zoneType = "raid",
        encounter = "nekzali",
        encounterLabel = "Nek'zali",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sentinels"] = {
        zoneType = "raid",
        encounter = "sentinels",
        encounterLabel = "Sentinels",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:vashnik"] = {
        zoneType = "raid",
        encounter = "vashnik",
        encounterLabel = "Vashnik",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:explorers"] = {
        zoneType = "raid",
        encounter = "explorers",
        encounterLabel = "Explorers",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:sszorak"] = {
        zoneType = "raid",
        encounter = "sszorak",
        encounterLabel = "Sszorak",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-twin-fangs"] = {
        zoneType = "raid",
        encounter = "the-twin-fangs",
        encounterLabel = "The Twin Fangs",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:the-coiled-altar"] = {
        zoneType = "raid",
        encounter = "the-coiled-altar",
        encounterLabel = "The Coiled Altar",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzM2MzYmZGbMZGMTDwMAzsZGmNDAZMWAwMDYMzMjZjZ2WGgZwA",
            recommended = true,
          },
        },
      },
      ["raid:heroic:nymrissa"] = {
        zoneType = "raid",
        encounter = "nymrissa",
        encounterLabel = "Nymrissa",
        difficulty = "heroic",
        difficultyLabel = "Heroic",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
      ["raid:normal:ulatek"] = {
        zoneType = "raid",
        encounter = "ulatek",
        encounterLabel = "Ula'tek",
        difficulty = "normal",
        difficultyLabel = "Normal",
        builds = {
          {
            heroTalent = "Archon",
            exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZY2MAkxYBAzAMmZmxsNmZbZAmBDA",
            recommended = true,
          },
        },
      },
    },
  },
}
