-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["PRIEST"] = {
  ["discipline"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 273778,
              name = "Polished Lightwood Channeler",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 271555,
              name = "Cosmic Penitent's Truesight",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271558,
              name = "Cosmic Penitent's Eclipsing Robes",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 250052,
              name = "Blind Oath's Touch",
            },
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249808,
              name = "Litany of Lightblind Wrath",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 251188,
              name = "Doompetal",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 271555,
              name = "Cosmic Penitent's Truesight",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271558,
              name = "Cosmic Penitent's Eclipsing Robes",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 250052,
              name = "Blind Oath's Touch",
            },
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249920,
              name = "Eye of Midnight",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
  ["holy"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 249293,
              name = "Weight of Command",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 250051,
              name = "Blind Oath's Winged Crest",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271558,
              name = "Cosmic Penitent's Eclipsing Robes",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271556,
              name = "Cosmic Penitent's Celestial Grips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 268292,
              name = "Sporelord's Mycelial Insignia",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 249293,
              name = "Weight of Command",
            },
          },
          {
            item = {
              itemId = 245769,
              name = "Aln'hara Lantern",
            },
          },
          {
            item = {
              itemId = 250051,
              name = "Blind Oath's Winged Crest",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271558,
              name = "Cosmic Penitent's Eclipsing Robes",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271556,
              name = "Cosmic Penitent's Celestial Grips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249336,
              name = "Signet of the Starved Beast",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 268292,
              name = "Sporelord's Mycelial Insignia",
            },
          },
        },
      },
    },
  },
  ["shadow"] = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251201,
              name = "Corespark Multitool",
            },
          },
          {
            item = {
              itemId = 271555,
              name = "Cosmic Penitent's Truesight",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271558,
              name = "Cosmic Penitent's Eclipsing Robes",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 250052,
              name = "Blind Oath's Touch",
            },
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 251201,
              name = "Corespark Multitool",
            },
          },
          {
            item = {
              itemId = 271555,
              name = "Cosmic Penitent's Truesight",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271553,
              name = "Cosmic Penitent's Echoing Screams",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 250054,
              name = "Blind Oath's Raiment",
            },
          },
          {
            item = {
              itemId = 239648,
              name = "Martyr's Bindings",
            },
            bis = true,
          },
          {
            item = {
              itemId = 271556,
              name = "Cosmic Penitent's Celestial Grips",
            },
            bis = true,
          },
          {
            item = {
              itemId = 239664,
              name = "Arcanoweave Cord",
            },
          },
          {
            item = {
              itemId = 271554,
              name = "Enveloping Legwraps of the Cosmic Penitent",
            },
            bis = true,
          },
          {
            item = {
              itemId = 268282,
              name = "Luxurious Loamstriders",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
}
