-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: icy-veins.com
ClassCodexIcyVeinsTalentData = ClassCodexIcyVeinsTalentData or {}
ClassCodexIcyVeinsTalentData["PRIEST"] = {
  ["discipline"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Voidweaver Raid",
        exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMmxyYmBzgZbmtZmZmZmBAAAAAAAAAgZYZGMzMDzYmBMNTzMYmBAAY2mtFwYzAAwYMzYwMYmBjgB",
      },
      {
        context = "Mythic+",
        buildLabel = "Oracle Mythic+",
        exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMDWmZMmBmZbmtZmZmxMDAAAAAAAAAgZYZGMzMzwYmBbmmJGgZWwQYMLDwYwCAAMmZmxgZAmZGBzA",
      },
      {
        context = "Leveling",
        buildLabel = "Discipline Level 80 Midnight Leveling",
        exportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsYMzGjxYmZMbsNzMzMzAAAAAAAAAAgBLzgZmZwYmBbmmpZAzAAAYbWAGbGAAGDzYwMYmBjmB",
        leveling = true,
      },
    },
  },
  ["holy"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Archon",
        exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAgZmlxYMzMDzMzYZGmBAAAwwsMDzMzMMDzYAzUAgZWMDziBAGD2MzMLAaGzMGDzMbLDwAGA",
      },
      {
        context = "General",
        buildLabel = "Archon",
        exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAMMzsMgZmZYmZGLzMzMAAAAGzsMDmZmxmxMjBMTBAmZzMMbGAYMYzMjFANjZGjBzstMADYA",
      },
      {
        context = "Delves",
        buildLabel = "Oracle",
        exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAADAAAAAAgZmxsMMjZGDzwYZmZmBAAAwYmlZwMzM2MmZMgZKAmZBDhxsNAjBWMzMLAMjZGjBzAMzMgB",
      },
      {
        context = "Leveling",
        buildLabel = "Holy Priest Level 80 Midnight Leveling",
        exportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAMMzsMmxMzYMzALzMzMAAAAmZsNDGPwM2MGjZDmpAYmFMEGWGgBYxMmFAmxMMzgZAMjBA",
        leveling = true,
      },
    },
  },
  ["shadow"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Archon",
        exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA",
      },
      {
        context = "General",
        buildLabel = "Voidweaver",
        exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGzGzgZGMDGA",
      },
      {
        context = "Delves",
        buildLabel = "Voidweaver",
        exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYmx2MYmZmZDZGLb0AMzMDAEgZb2WAzGDAMwMzMzMbMDmZwMYA",
      },
      {
        context = "Raid",
        buildLabel = "No 4pc Season 2",
        exportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZ0sZAIjxCAmBYMzMjZbMz2yAMDGA",
      },
      {
        context = "General",
        buildLabel = "No 4pc Season 2",
        exportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYGgZ2MjmNDAZMWAwMAjZmZMbjZ2WGgZwA",
      },
      {
        context = "Raid",
        buildLabel = "No 4pc Season 2",
        exportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMsNzMmZmxGyMWMTDwMzMAQAmtZbJY2YAmBYMzMjZbMDmZwMYA",
      },
      {
        context = "General",
        buildLabel = "No 4pc Season 2",
        exportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAghZxMGbzMmZWmZYmx2MGzMzYDZGLmpBYmZGAIAz2stEMbMAwgxMzMmtxMYmBzgB",
      },
      {
        context = "Leveling",
        buildLabel = "Archon Level 80 Starting Talents",
        exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAAzmBAAAAAAAAAAAwYsYGjlxYmZzwMDMYmZGLIzYxMNAGgZWMDzmBgMGLAYmZmhxMzMzsxMAYGA",
        leveling = true,
      },
      {
        context = "Leveling",
        buildLabel = "Archon Level 80 Starting Talents",
        exportString = "CIQAAAAAAAAAAAAAAAAAAAAAAAzmBAAAAAAAAAAAwYsYGjlxYmZzMmZgBzMzYBZGLmpBwMzAABY2mNgZDAjZmhxMzMzsxMwMYGA",
        leveling = true,
      },
    },
  },
}
