-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonStats = ClassCodexArchonStats or {}
ClassCodexArchonStats["DRUID"] = {
  balance = {
    ["Mythic+"] = {
      targets = {
        crit = 669,
        haste = 770,
        mastery = 996,
        versatility = 183,
      },
    },
    Raid = {
      targets = {
        crit = 672,
        haste = 761,
        mastery = 1073,
        versatility = 164,
      },
    },
  },
  feral = {
    ["Mythic+"] = {
      targets = {
        crit = 595,
        haste = 816,
        mastery = 1028,
        versatility = 178,
      },
    },
    Raid = {
      targets = {
        crit = 584,
        haste = 834,
        mastery = 997,
        versatility = 181,
      },
    },
  },
  guardian = {
    ["Mythic+"] = {
      targets = {
        crit = 517,
        haste = 1025,
        mastery = 621,
        versatility = 373,
      },
    },
    Raid = {
      targets = {
        crit = 517,
        haste = 1113,
        mastery = 653,
        versatility = 359,
      },
    },
  },
  restoration = {
    ["Mythic+"] = {
      targets = {
        crit = 274,
        haste = 1145,
        mastery = 1034,
        versatility = 195,
      },
    },
    Raid = {
      targets = {
        crit = 251,
        haste = 1275,
        mastery = 1074,
        versatility = 149,
      },
    },
  },
}
