-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexCraftingData = ClassCodexCraftingData or {}
ClassCodexCraftingData["DRUID"] = {
  ["balance"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 0,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 244601,
          name = "&nbsp;",
        },
      },
    },
  },
  ["feral"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
          bis = true,
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 245771,
          name = "Aln'hara Pikestaff",
        },
        {
          itemId = 237847,
          name = "Blood Knight's Impetus",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 251513,
          name = "Loa Worshiper's Band",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
          bis = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 251513,
          name = "Loa Worshiper's Band",
        },
        {
          itemId = 237847,
          name = "Blood Knight's Impetus",
        },
        {
          itemId = 245771,
          name = "Aln'hara Pikestaff",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251488,
          name = "&nbsp;",
        },
      },
    },
  },
  ["guardian"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 245771,
          name = "Aln'hara Pikestaff",
        },
        {
          itemId = 237847,
          name = "Blood Knight's Impetus",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
      },
      embellishments = {
        {
          itemId = 0,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 245771,
          name = "Aln'hara Pikestaff",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 237848,
          name = "Blood Knight's Mercy",
        },
        {
          itemId = 244585,
          name = "Smuggler's Leather Footpads",
        },
        {
          itemId = 244586,
          name = "Smuggler's Leather Wristbands",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
        {
          itemId = 244594,
          name = "Smuggler's Reinforced Pants",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 273069,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
        {
          itemId = 244675,
          name = "&nbsp;",
        },
      },
    },
  },
  ["restoration"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          popular = true,
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 237849,
          name = "Magister's Valediction",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
        {
          itemId = 244574,
          name = "Silvermoon Agent's Leggings",
        },
        {
          itemId = 244571,
          name = "Silvermoon Agent's Cover",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244604,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 244601,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 244608,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244576,
          name = "Silvermoon Agent's Deflectors",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244569,
          name = "Silvermoon Agent's Sneakers",
        },
        {
          itemId = 244573,
          name = "Silvermoon Agent's Utility Belt",
        },
        {
          itemId = 245770,
          name = "Aln'hara Cane",
        },
        {
          itemId = 245769,
          name = "Aln'hara Lantern",
        },
        {
          itemId = 244570,
          name = "Silvermoon Agent's Coat",
        },
        {
          itemId = 240949,
          name = "Masterwork Sin'dorei Band",
        },
        {
          itemId = 237849,
          name = "Magister's Valediction",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244572,
          name = "Silvermoon Agent's Mantle",
        },
        {
          itemId = 244575,
          name = "Silvermoon Agent's Handwraps",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 245874,
          name = "&nbsp;",
        },
        {
          itemId = 244604,
          name = "&nbsp;",
        },
        {
          itemId = 251073,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 240165,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
      },
    },
  },
}
