-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexArchonGearData = ClassCodexArchonGearData or {}
ClassCodexArchonGearData["DRUID"] = {
  balance = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250022,
              name = "Seedpods of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
              name = "Enigmatic Dreamwatcher's Lunar Raiment",
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271529,
              name = "Enigmatic Dreamwatcher's Gauntlets",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
              name = "Enigmatic Dreamwatcher's Leggings",
            },
          },
          {
            item = {
              itemId = 250026,
              name = "Rootslippers of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 273778,
              name = "Polished Lightwood Channeler",
            },
          },
          {
            item = {
              itemId = 245769,
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271526,
              name = "Enigmatic Dreamwatcher's Plumage",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
              name = "Enigmatic Dreamwatcher's Lunar Raiment",
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271529,
              name = "Enigmatic Dreamwatcher's Gauntlets",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 250023,
              name = "Phloemwraps of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 250026,
              name = "Rootslippers of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251217,
              name = "Occlusion of Void",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249346,
              name = "Vaelgor's Final Stare",
            },
          },
        },
      },
    },
  },
  feral = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251077,
              name = "Roostwarden's Bough",
            },
          },
          {
            item = {
              itemId = 250024,
              name = "Branches of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271526,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271529,
              name = "Enigmatic Dreamwatcher's Gauntlets",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
            },
          },
          {
            item = {
              itemId = 250026,
              name = "Rootslippers of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 193701,
              name = "Algeth'ar Puzzle Box",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 249302,
              name = "Inescapable Reach",
            },
          },
          {
            item = {
              itemId = 271528,
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250022,
              name = "Seedpods of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
            },
          },
          {
            item = {
              itemId = 244576,
            },
          },
          {
            item = {
              itemId = 271529,
              name = "Enigmatic Dreamwatcher's Gauntlets",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
            },
          },
          {
            item = {
              itemId = 250026,
              name = "Rootslippers of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 193701,
              name = "Algeth'ar Puzzle Box",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
        },
      },
    },
  },
  guardian = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 249278,
              name = "Alnscorned Spire",
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271526,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
            },
          },
          {
            item = {
              itemId = 244576,
              name = "Silvermoon Agent's Deflectors",
            },
          },
          {
            item = {
              itemId = 250025,
              name = "Arbortenders of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
            },
          },
          {
            item = {
              itemId = 251210,
              name = "Eclipse Espadrilles",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 268292,
              name = "Sporelord's Mycelial Insignia",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 249278,
              name = "Alnscorned Spire",
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271526,
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
            },
          },
          {
            item = {
              itemId = 244576,
              name = "Silvermoon Agent's Deflectors",
            },
          },
          {
            item = {
              itemId = 250025,
              name = "Arbortenders of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
            },
          },
          {
            item = {
              itemId = 244569,
              name = "Silvermoon Agent's Sneakers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 249920,
              name = "Eye of Midnight",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 260235,
              name = "Umbral Plume",
            },
          },
        },
      },
    },
  },
  restoration = {
    bisGear = {
      {
        label = "Mythic+",
        slots = {
          {
            item = {
              itemId = 251201,
              name = "Corespark Multitool",
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 271526,
              name = "Enigmatic Dreamwatcher's Plumage",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
              name = "Enigmatic Dreamwatcher's Lunar Raiment",
            },
          },
          {
            item = {
              itemId = 244576,
              name = "Silvermoon Agent's Deflectors",
            },
          },
          {
            item = {
              itemId = 250025,
              name = "Arbortenders of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 244573,
              name = "Silvermoon Agent's Utility Belt",
            },
          },
          {
            item = {
              itemId = 271527,
              name = "Enigmatic Dreamwatcher's Leggings",
            },
          },
          {
            item = {
              itemId = 244569,
              name = "Silvermoon Agent's Sneakers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249809,
              name = "Locus-Walker's Ribbon",
            },
          },
        },
      },
      {
        label = "Raid",
        slots = {
          {
            item = {
              itemId = 245770,
              name = "Aln'hara Cane",
            },
          },
          {
            item = {
              itemId = 271528,
              name = "Enigmatic Dreamwatcher's Somnolent Stare",
            },
          },
          {
            item = {
              itemId = 268291,
              name = "Rotmire's Sporeheart",
            },
          },
          {
            item = {
              itemId = 250022,
              name = "Seedpods of the Luminous Bloom",
            },
          },
          {
            item = {
              itemId = 239656,
              name = "Adherent's Silken Shroud",
            },
          },
          {
            item = {
              itemId = 271531,
              name = "Enigmatic Dreamwatcher's Lunar Raiment",
            },
          },
          {
            item = {
              itemId = 244576,
              name = "Silvermoon Agent's Deflectors",
            },
          },
          {
            item = {
              itemId = 271529,
              name = "Enigmatic Dreamwatcher's Gauntlets",
            },
          },
          {
            item = {
              itemId = 268286,
              name = "Sash of the Putrid Giant",
            },
          },
          {
            item = {
              itemId = 271527,
              name = "Enigmatic Dreamwatcher's Leggings",
            },
          },
          {
            item = {
              itemId = 244569,
              name = "Silvermoon Agent's Sneakers",
            },
          },
          {
            item = {
              itemId = 268290,
              name = "Sporecaller's Blooming Loop",
            },
          },
          {
            item = {
              itemId = 251093,
              name = "Omission of Light",
            },
          },
          {
            item = {
              itemId = 249343,
              name = "Gaze of the Alnseer",
            },
          },
          {
            item = {
              itemId = 249809,
              name = "Locus-Walker's Ribbon",
            },
          },
        },
      },
    },
  },
}
