-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: icy-veins.com
ClassCodexIcyVeinsTalentData = ClassCodexIcyVeinsTalentData or {}
ClassCodexIcyVeinsTalentData["DRUID"] = {
  ["balance"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Elune's",
        exportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZGGzYhlZWmZMmZDDAGbLzMYMbDgJAAAALMzMzgNjZMmBAwMDWGA",
      },
      {
        context = "General",
        buildLabel = "Elune's",
        exportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZmFzMjFWmZZMmZsgBAjttZGMmtBwEAAAgFmZmZwmxMGzAAYmBGA",
      },
      {
        context = "Delves",
        buildLabel = "Keeper",
        exportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmZDgZZmtZWmxMzGLzYMGzshBADw22YBTzMbDAAAA2MzMzMYzYGjBgZGAYA",
      },
      {
        context = "General",
        buildLabel = "Keeper of the Grove Cleave Build",
        exportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmlZmZmBMDjZWmZZGzYhlZMmZmxCGAMALbjFMNzsMAAAAYjZmZGsZgxMAmZAgBA",
      },
      {
        context = "Leveling",
        buildLabel = "Balance Druid Level 80 Midnight Leveling",
        exportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDMmFmZmZDYMmZZsNjZmNWmxYMYDDAGgttxCmmZWGAAAAsxMzMD2MwYAYmBAGA",
        leveling = true,
      },
    },
  },
  ["feral"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Wildstalker",
        exportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYMjxYmZMmtFWGbzMzYmZAAAAYLY2MMmZUzYWmZmZGjZMAAAAAAMwAAAAAAMbzs0sNzyGYmHAYxMYAAMzAgB",
      },
      {
        context = "Raid",
        buildLabel = "Wildstalker",
        exportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZMzGzMzMGz2yYZsNjZmHYmBAAAgtgZzwYmRNjZZmZmZMmxAAAAAAwADAAAAAwsNzSzyMLbgZeAgFzgBAwMDAGA",
      },
      {
        context = "Mythic+",
        buildLabel = "Druid of the Claw",
        exportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYLY2M8AmZUzYWMzMzsMmxAAAAAAwADAAAgmZZWmZmBAsAzMDwCDGAAAzshB",
      },
      {
        context = "Delves",
        buildLabel = "Druid of the Claw",
        exportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZYmxMzMzsZsNz2MmZegZGAAAA2CmNDPgZG1MmlxMzMLjZYAAAAAAMwAAAAoZWmlZmZAALwMzAswgBAAwMbYA",
      },
      {
        context = "Leveling",
        buildLabel = "Level 80 Starting Talents",
        exportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDzMmZmZmNjtZ2mZmZegZGAAAA2CGGGzMqZMLjZmZMmBAAAAAAGYAAAAkxsMmZAALgZGgFGMAAAmZDA",
        leveling = true,
      },
    },
  },
  ["guardian"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Druid of the Claw",
        exportString = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwYMzmZZGMLLDMbwoJamZWmZmZGjZMDAAAAAYGLzAAAAgmZZWmZmBAwCmZAWMDGwmFDAmZDG",
      },
      {
        context = "General",
        buildLabel = "Elunes Chosen",
        exportString = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZml5BmZMziZxwMLLDMbGGNRmZWmZmZmlxMGAAAAAgZsYAbbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA",
      },
      {
        context = "Delves",
        buildLabel = "Elunes Chosen",
        exportString = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwMjZWMLGmZZZgZzwoJyMzyMzMzsMmxAAAAAAMjlZALbzMYMLDgJAAAgNMzAsYGMgNLAMzAYA",
      },
      {
        context = "Leveling",
        buildLabel = "Guardian Druid Level 80 Midnight Leveling",
        exportString = "CgGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmxsMPwYMWMbzMPgZZZAbGGNRzMzyMzMzYMDAAAAAADbzAW2mZwYWGATAAAAbYMALmBDGssNAAA",
        leveling = true,
      },
    },
  },
  ["restoration"] = {
    talents = {
      {
        context = "Raid",
        buildLabel = "Wildstalker Raid",
        exportString = "CkGADBD3hSPCL9Y9gz68WcKvMMjxMLzMjZmxsNMYmNjFmBAAAAAAAAAAbDa2YMNzY4BMLzMzMDDzAAAAAAAAAAIAAgZbmlmtZ2sxYmZYmBGNDAwMDADA",
      },
      {
        context = "Mythic+",
        buildLabel = "Wildstalker Mythic+",
        exportString = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNMMzsMsZbGAAAAAAAAAAsMoZzw0MjZwsYmZmZZGGDAAAAAAAGAAAAAMbzs1sNziNGzMwMbgmBAYmBgB",
      },
      {
        context = "Delves",
        buildLabel = "Wildstalker Delves",
        exportString = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmxYGzMjZbmZYYhZx2MAAAAAAAAAAYbQzmhpZMzYMLmZmZWmhxAAAAAAAYMAAEAAwsMzWzyML2gZeAMjFQzAAMzAwA",
      },
      {
        context = "Leveling",
        buildLabel = "Restoration Druid Level 80 Midnight Leveling",
        exportString = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZZMjZmxsNzMglZsYbGAAAAAAAAAAsNoZjxkhZmxsZmZmZZGYAAAAAAAwAAAAAghZrZZsYDmZgZWAZAAmZAA",
        leveling = true,
      },
    },
  },
}
