-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: archon.gg | scraped 2026-08-20T12:00:00Z
ClassCodexCraftingData = ClassCodexCraftingData or {}
ClassCodexCraftingData["HUNTER"] = {
  ["beast-mastery"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 265337,
          name = "Aln'hara Sprigshot",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251490,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 265337,
          name = "Aln'hara Sprigshot",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 239674,
          name = "Courtly Cloak",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244602,
          name = "Ranger-General's Grips",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 251513,
          name = "&nbsp;",
        },
      },
    },
  },
  ["marksmanship"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 265337,
          name = "Aln'hara Sprigshot",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
          popular = true,
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 265337,
          name = "Aln'hara Sprigshot",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
      },
    },
  },
  ["survival"] = {
    mythicPlus = {
      crafts = {
        {
          itemId = 237837,
          name = "Farstrider's Mercy",
          popular = true,
        },
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 237847,
          name = "Blood Knight's Impetus",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 273069,
          name = "&nbsp;",
        },
        {
          itemId = 273069,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 244609,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
      },
    },
    raid = {
      crafts = {
        {
          itemId = 244584,
          name = "Farstrider's Plated Bracers",
          bis = true,
          popular = true,
        },
        {
          itemId = 237837,
          name = "Farstrider's Mercy",
          popular = true,
        },
        {
          itemId = 239656,
          name = "Adherent's Silken Shroud",
          popular = true,
        },
        {
          itemId = 244581,
          name = "Farstrider's Trophy Belt",
          bis = true,
        },
        {
          itemId = 244611,
          name = "World Tender's Barkclasp",
        },
        {
          itemId = 244610,
          name = "World Tender's Rootslippers",
        },
        {
          itemId = 244577,
          name = "Farstrider's Razor Talons",
        },
        {
          itemId = 237847,
          name = "Blood Knight's Impetus",
        },
        {
          itemId = 240950,
          name = "Masterwork Sin'dorei Amulet",
        },
        {
          itemId = 244580,
          name = "Farstrider's Brilliant Plumes",
        },
        {
          itemId = 244578,
          name = "Farstrider's Scouting Vest",
        },
        {
          itemId = 244609,
          name = "World Tender's Trunkplate",
        },
        {
          itemId = 244583,
          name = "Farstrider's Sharpened Claws",
        },
        {
          itemId = 244745,
          name = "Aetherlume Vision Shroud",
        },
      },
      embellishments = {
        {
          itemId = 240167,
          name = "&nbsp;",
          popular = true,
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 0,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 245876,
          name = "&nbsp;",
        },
        {
          itemId = 273069,
          name = "&nbsp;",
        },
        {
          itemId = 273069,
          name = "&nbsp;",
        },
        {
          itemId = 240167,
          name = "&nbsp;",
        },
        {
          itemId = 244610,
          name = "&nbsp;",
        },
        {
          itemId = 244611,
          name = "&nbsp;",
        },
        {
          itemId = 251073,
          name = "&nbsp;",
        },
      },
    },
  },
}
