-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: murlok.io
ClassCodexMurlokPvp = ClassCodexMurlokPvp or {}
ClassCodexMurlokPvp["HUNTER"] = {
  ["beast-mastery"] = {
    bracket = "solo",
    statPriority = {
      {
        key = "versatility",
        rating = 1254,
      },
      {
        key = "mastery",
        rating = 696,
      },
      {
        key = "haste",
        rating = 342,
      },
      {
        key = "avoidance",
        rating = 3,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 270539,
        },
        {
          itemId = 270538,
        },
        {
          itemId = 239678,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 271493,
        },
        {
          itemId = 270495,
        },
        {
          itemId = 244567,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
        {
          itemId = 257748,
        },
      },
      Neck = {
        {
          itemId = 270532,
        },
        {
          itemId = 240952,
        },
      },
      Prismatic = {
        {
          itemId = 240902,
        },
        {
          itemId = 241144,
        },
        {
          itemId = 240918,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270558,
        },
        {
          itemId = 270556,
        },
        {
          itemId = 245752,
        },
      },
      Waist = {
        {
          itemId = 244565,
        },
        {
          itemId = 270486,
        },
      },
      Wrist = {
        {
          itemId = 270485,
        },
        {
          itemId = 244568,
        },
        {
          itemId = 244741,
        },
      },
    },
  },
  ["marksmanship"] = {
    bracket = "solo",
    statPriority = {
      {
        key = "versatility",
        rating = 1101,
      },
      {
        key = "mastery",
        rating = 869,
      },
      {
        key = "haste",
        rating = 248,
      },
      {
        key = "avoidance",
        rating = 42,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 270539,
        },
        {
          itemId = 239678,
        },
        {
          itemId = 270538,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 271493,
        },
        {
          itemId = 244567,
        },
        {
          itemId = 270495,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
        {
          itemId = 257748,
        },
      },
      Neck = {
        {
          itemId = 240952,
        },
        {
          itemId = 270532,
        },
      },
      Prismatic = {
        {
          itemId = 240895,
        },
        {
          itemId = 240902,
        },
        {
          itemId = 241144,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270558,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 244565,
        },
        {
          itemId = 270486,
        },
      },
      Wrist = {
        {
          itemId = 270485,
        },
        {
          itemId = 244568,
        },
      },
    },
  },
  ["survival"] = {
    bracket = "solo",
    statPriority = {
      {
        key = "versatility",
        rating = 1002,
      },
      {
        key = "mastery",
        rating = 820,
      },
      {
        key = "haste",
        rating = 401,
      },
    },
    bisGear = {
      Back = {
        {
          itemId = 239678,
        },
        {
          itemId = 270539,
        },
      },
      Chest = {
        {
          itemId = 0,
        },
      },
      Feet = {
        {
          itemId = 0,
        },
      },
      Hands = {
        {
          itemId = 270495,
        },
        {
          itemId = 270494,
        },
      },
      Head = {
        {
          itemId = 0,
        },
      },
      Legs = {
        {
          itemId = 244641,
        },
        {
          itemId = 244645,
        },
      },
      ["Main Hand"] = {
        {
          itemId = 0,
        },
      },
      Neck = {
        {
          itemId = 240952,
        },
      },
      ["Off Hand"] = {
        {
          itemId = 270458,
        },
      },
      Prismatic = {
        {
          itemId = 240902,
        },
        {
          itemId = 0,
        },
        {
          itemId = 241144,
        },
      },
      Rings = {
        {
          itemId = 0,
        },
      },
      Shoulders = {
        {
          itemId = 0,
        },
      },
      Trinkets = {
        {
          itemId = 270559,
        },
        {
          itemId = 270556,
        },
      },
      Waist = {
        {
          itemId = 244565,
        },
        {
          itemId = 270486,
        },
      },
      Wrist = {
        {
          itemId = 244568,
        },
        {
          itemId = 270485,
        },
      },
    },
  },
}
