-- Generated by tools/ in this repository. Do not edit by hand.
-- Source: icy-veins.com
ClassCodexIcyVeinsTalentData = ClassCodexIcyVeinsTalentData or {}
ClassCodexIcyVeinsTalentData["HUNTER"] = {
  ["beast-mastery"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Pack Leader",
        exportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwwMsBAgZYMzyMDzYmxMMzYMzwMjZMziZmxMmBjpZAAAAAzAAAwYmZAmZjxGMLgtBgBA",
      },
      {
        context = "Mythic+",
        buildLabel = "Pack Leader",
        exportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzsYGzMzMjZGMzYmhZGzMzYbmZMjZYZMNDAAAAAAAA8AjxAmZjAmFw2AwA",
      },
      {
        context = "Delves",
        buildLabel = "Pack Leader",
        exportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzsYGzMzMjZGMzYmhZGzMzgxYGzMMmGAAAAAAAAYmxYAzsRwyMLgtBgBA",
      },
    },
  },
  ["marksmanship"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Sentinel",
        exportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwYbZmZmZmZmZWYmlBzAAAGzMjBwM22gBYjZ2mxAA",
      },
      {
        context = "Raid",
        buildLabel = "Sentinel",
        exportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwstZmZmZmZmZWYmlhZAAAGzMjBwM22gBYjZ2mxAA",
      },
      {
        context = "Mythic+",
        buildLabel = "Sentinel",
        exportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzMzYbGzMjZYZMNjBzy2yMzMzMzMzswMLDzAAA4BGjBgZsBGgNmZbGD",
      },
      {
        context = "Delves",
        buildLabel = "Sentinel",
        exportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzMzgxMzYmhx0wgZZbZmZmZmZmZWwsNMDAAwMjxAwM2wyMAbMz2MG",
      },
    },
  },
  ["survival"] = {
    talents = {
      {
        context = "General",
        buildLabel = "Sentinel",
        exportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZMzMGzyAAAAAAwMmxMLmxYGzgx0MAAAADAmxyyMzsYMzMjZmBAzYZDGDjNDAA",
      },
      {
        context = "Mythic+",
        buildLabel = "Sentinel",
        exportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMjtZMmxMsMmmBAAAYAgxyyMjFMzMegxYAYGbgxYmZzAAA",
      },
      {
        context = "Delves",
        buildLabel = "Sentinel",
        exportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMDGjZMzwYaAAAAAAGLLzMWwMzMzYMAMjNsMjxMzmBAAA",
      },
    },
  },
}
