#!/usr/bin/env python3
"""Rebuild and verify the external guide links in Data/*/sources.lua.

Three of the four sources use stable, spec-derived URLs (Icy Veins,
Murlok, Wowhead's BiS page). Two do not:

  * Wowhead's seasonal guide page carries the season in its slug
    ("midnight-season-1" -> "midnight-season-2").
  * Archon renames its Mythic+ difficulty bracket every season
    ("high-keys" -> "10"). The current slug is read out of the freshly
    scraped Data/*/archon-talents.lua rather than guessed.

Every rebuilt link is then requested. Wowhead's WAF rejects clients that
do not send a full browser header set; ccutil sends them, so all 280
links verify directly. The 403 path is kept as a distinct outcome rather
than a failure, because if Wowhead tightens that again a 403 says
"blocked", not "gone", and the two must not be confused.

Usage:
    python3 tools/refresh_sources.py --wowhead-season midnight-season-2
    python3 tools/refresh_sources.py --check-only
"""

from __future__ import annotations

import argparse
import concurrent.futures as futures
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ccutil import CLASS_DIRS, DATA, head_status, log, lua_str, write_lua  # noqa: E402

SOURCE_ORDER = ("wowhead", "icyveins", "archon", "murlok")
KEY_ORDER = {
    "wowhead": ("guide", "bis"),
    "icyveins": ("bis", "talents", "leveling"),
    "archon": ("build",),
    "murlok": ("pvp",),
}

_SPEC = re.compile(r'^\s*\["([a-z-]+)"\]\s*=\s*\{', re.M)
_ENTRY = re.compile(r'(\w+)\s*=\s*\{([^}]*)\}')
_PAIR = re.compile(r'(\w+)\s*=\s*"([^"]+)"')
_SEASON = re.compile(r"/[a-z]+-season-\d+$")


def parse_sources(path: Path) -> dict[str, dict[str, dict[str, str]]]:
    """Read a sources.lua back into {spec: {source: {key: url}}}."""
    text = path.read_text(encoding="utf-8")
    specs: dict[str, dict[str, dict[str, str]]] = {}
    marks = [(m.group(1), m.start()) for m in _SPEC.finditer(text)]
    for i, (spec, start) in enumerate(marks):
        end = marks[i + 1][1] if i + 1 < len(marks) else len(text)
        block = text[start:end]
        entry: dict[str, dict[str, str]] = {}
        for src, body in _ENTRY.findall(block):
            if src in SOURCE_ORDER:
                entry[src] = dict(_PAIR.findall(body))
        if entry:
            specs[spec] = entry
    return specs


def archon_bracket() -> str:
    """The Mythic+ difficulty slug the scraped Archon data was built with."""
    seen: dict[str, int] = {}
    for path in DATA.glob("*/archon-talents.lua"):
        for slug in re.findall(r'\["mythic-plus:([^:"]+):', path.read_text(encoding="utf-8")):
            seen[slug] = seen.get(slug, 0) + 1
    if not seen:
        raise SystemExit("no Archon data found — run refresh_archon.py first")
    return max(seen.items(), key=lambda kv: kv[1])[0]


def rebuild(links: dict[str, dict[str, str]], *, season: str,
            bracket: str) -> dict[str, dict[str, str]]:
    out = {src: dict(keys) for src, keys in links.items()}

    guide = out.get("wowhead", {}).get("guide")
    if guide and _SEASON.search(guide):
        out["wowhead"]["guide"] = _SEASON.sub(f"/{season}", guide)

    build = out.get("archon", {}).get("build")
    if build:
        out["archon"]["build"] = re.sub(
            r"(?P<head>/mythic-plus/overview/)[^/]+(?P<tail>/)",
            lambda m: f"{m['head']}{bracket}{m['tail']}", build)

    return out


def emit(path: Path, class_token: str, specs: dict[str, dict[str, dict[str, str]]],
         *, season: str) -> None:
    """Write sources.lua by hand: one compact line per source, as upstream had."""
    lines = [
        "-- Generated by tools/refresh_sources.py. Do not edit by hand.",
        f"-- Wowhead season slug: {season}",
        "ClassCodexSources = ClassCodexSources or {}",
        f"ClassCodexSources[{lua_str(class_token)}] = {{",
    ]
    for spec in sorted(specs):
        lines.append(f"  [{lua_str(spec)}] = {{")
        for src in SOURCE_ORDER:
            keys = specs[spec].get(src)
            if not keys:
                continue
            ordered = [k for k in KEY_ORDER[src] if k in keys]
            ordered += [k for k in keys if k not in ordered]
            body = ", ".join(f"{k} = {lua_str(keys[k])}" for k in ordered)
            lines.append(f"    {src} = {{ {body} }},")
        lines.append("  },")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--wowhead-season", default="midnight-season-2")
    ap.add_argument("--check-only", action="store_true")
    ap.add_argument("--jobs", type=int, default=8)
    ap.add_argument("--report", type=Path, help="write the link report as JSON")
    args = ap.parse_args()

    bracket = archon_bracket()
    log(f"Archon Mythic+ bracket from scraped data: {bracket!r}")
    log(f"Wowhead season slug: {args.wowhead_season!r}")

    all_links: list[tuple[str, str, str, str, str]] = []
    for class_dir, token in sorted(CLASS_DIRS.items()):
        path = DATA / class_dir / "sources.lua"
        specs = parse_sources(path)
        rebuilt = {spec: rebuild(links, season=args.wowhead_season, bracket=bracket)
                   for spec, links in specs.items()}
        if not args.check_only:
            emit(path, token, rebuilt, season=args.wowhead_season)
        for spec, links in rebuilt.items():
            for src, keys in links.items():
                for key, url in keys.items():
                    all_links.append((class_dir, spec, src, key, url))

    log(f"{len(all_links)} links across "
        f"{len({(c, s) for c, s, *_ in all_links})} specs")

    results: list[dict] = []
    with futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        jobs = {pool.submit(head_status, url): (c, s, src, key, url)
                for c, s, src, key, url in all_links}
        for fut in futures.as_completed(jobs):
            c, s, src, key, url = jobs[fut]
            status, final = fut.result()
            results.append({"class": c, "spec": s, "source": src, "key": key,
                            "url": url, "status": status, "final": final})

    ok = [r for r in results if r["status"] in (200, 206)]
    blocked = [r for r in results if r["source"] == "wowhead" and r["status"] == 403]
    redirected = [r for r in ok if r["final"].rstrip("/") != r["url"].rstrip("/")]
    bad = [r for r in results if r not in ok and r not in blocked]

    log(f"  {len(ok)} reachable, {len(blocked)} Wowhead (bot-blocked, unverified), "
        f"{len(bad)} failing")
    for r in redirected[:10]:
        log(f"  -> redirect {r['url']} => {r['final']}")
    for r in sorted(bad, key=lambda r: (r["source"], r["class"])):
        log(f"  FAIL {r['status']} {r['source']}/{r['key']} "
            f"{r['class']}/{r['spec']}: {r['url']}")

    if args.report:
        args.report.write_text(json.dumps(results, indent=1), encoding="utf-8")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
